-- RR_FXPresets: GENERATED by rr-vfx-lighting (vfx.py build, 2026-09-29) from presets/vfx.json.
-- Do not edit: change the JSON and rebuild. Palette colours use hex(); light levels use lvl() (intensities, not palette).
local function hex(h) return Color3.fromHex(h) end
local function lvl(r, g, b) return Color3.fromRGB(r, g, b) end

local function nr(a, b) return NumberRange.new(a, b) end
local function ns(t)
	local k = {}
	for i, p in ipairs(t) do k[i] = NumberSequenceKeypoint.new(p[1], p[2], p[3] or 0) end
	return NumberSequence.new(k)
end
local function cs(t)
	local k = {}
	for i, p in ipairs(t) do k[i] = ColorSequenceKeypoint.new(p[1], p[2]) end
	return ColorSequence.new(k)
end

local P = {}

P.meta = {
	speed_max = 50, -- gameplay.speed.fast (rr-bible)
	speeds = {slow = 20, normal = 35, fast = 50},
	wind_scale = 1,
	budget_status = "assumed (OQ-029 default A): not canon until the owner decides; re-measure at the alpha live check (tech.streaming.live_check)",
	tiers = {
		phone = {rate_scale = {[1] = 1, [2] = 0.7, [3] = 0.5}, post_off = {"BloomEffect", "SunRaysEffect", "DepthOfFieldEffect"}, live_particles = 400, burst_peak = 800},
		pc = {rate_scale = {[1] = 1, [2] = 1, [3] = 1}, post_off = {"DepthOfFieldEffect"}, live_particles = 1500, burst_peak = 2500},
	},
}

P.trails = {
	debris_smoke = {width = 0.9, props = {
		Lifetime = 0.6,
		MinLength = 0.1,
		FaceCamera = true,
		WidthScale = ns({{0, 1}, {1, 0.25}}),
		Transparency = ns({{0, 0.25}, {1, 1}}),
		Color = cs({{0, hex("15181B")}, {1, hex("8C8680")}}),
		LightEmission = 0,
		LightInfluence = 1,
	}},
	debris_spark = {width = 0.35, props = {
		Lifetime = 0.25,
		MinLength = 0.05,
		FaceCamera = true,
		WidthScale = ns({{0, 1}, {1, 0.1}}),
		Transparency = ns({{0, 0}, {1, 1}}),
		Color = cs({{0, hex("FFD95E")}, {1, hex("FF7A22")}}),
		LightEmission = 1,
		LightInfluence = 0,
	}},
	split_streak = {width = 0.4, props = {
		Lifetime = 0.12,
		MinLength = 0.05,
		FaceCamera = true,
		WidthScale = ns({{0, 1}, {1, 0}}),
		Transparency = ns({{0, 0}, {1, 1}}),
		Color = cs({{0, hex("FF7A22")}, {1, hex("363A42")}}),
		LightEmission = 0.6,
		LightInfluence = 0,
	}},
}

P.presets = {
	headlamp = {
		kind = "loop", priority = 2, anchor = "Headlamp", start = "on",
		use = "loco headlamp for tunnels and night: spot light plus a soft beam cone (glow colour style.thumb.glow; tunnel and night use proposed)",
		layers = {
			{name = "spot", class = "SpotLight", offset = Vector3.new(0.2, 0, 0), dir = Vector3.new(1, -0.08, 0), props = {
				Brightness = 3,
				Range = 60,
				Angle = 50,
				Face = Enum.NormalId.Front,
				Color = hex("FFF6C8"),
				Shadows = false,
			}},
			{name = "cone", class = "Beam", offset = Vector3.new(0.3, 0, 0), a1 = Vector3.new(40, -3, 0), props = {
				Width0 = 1.5,
				Width1 = 22,
				Segments = 1,
				FaceCamera = true,
				Transparency = ns({{0, 0.72}, {1, 1}}),
				Color = cs({{0, hex("FFF6C8")}, {1, hex("FFF6C8")}}),
				LightEmission = 1,
				LightInfluence = 0,
			}},
		},
	},
	split_explosion = {
		kind = "burst", priority = 1, anchor = "SplitCore", start = "off",
		use = "carriage split: big slapstick burst in the tear (flash, 6-puff fireball cooling to charcoal in place, 6 round soot puffs rising about 12 studs/s, flat cream shock dust, chunks and hot bits on orange streaks); owner decision 2026-09-29 (C10 'I want a big explosion aswell') overrides the OQ-028 default for the carriage split only",
		layers = {
			{name = "flash", class = "PointLight", offset = Vector3.new(0, 2, 0), pulse = {peak = 8, duration = 0.4}, props = {
				Brightness = 0,
				Range = 45,
				Color = hex("FFE7A6"),
				Shadows = false,
			}},
			{name = "core", class = "ParticleEmitter", offset = Vector3.new(0, 3, 0), dir = Vector3.new(0, 1, 0), emit = 6, props = {
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 0,
				Lifetime = nr(0.7, 0.85),
				Speed = nr(66, 80),
				SpreadAngle = Vector2.new(80, 80),
				Drag = 4,
				WindAffectsDrag = true,
				Size = ns({{0, 13}, {1, 19}}),
				Transparency = ns({{0, 0}, {0.78, 0.05}, {1, 1}}),
				Color = cs({{0, hex("FFFFFF")}, {0.12, hex("FFE7A6")}, {0.3, hex("F2C230")}, {0.6, hex("FF7A22")}, {0.88, hex("363A42")}, {1, hex("15181B")}}),
				LightEmission = 0.6,
				LightInfluence = 0,
				Rotation = nr(0, 360),
				RotSpeed = nr(-60, 60),
			}},
			{name = "soot", class = "ParticleEmitter", offset = Vector3.new(0, 7, 0), dir = Vector3.new(0, 1, 0), emit = 5, delay = 0.1, props = {
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 0,
				Lifetime = nr(2.4, 3.4),
				Speed = nr(14, 18),
				SpreadAngle = Vector2.new(45, 45),
				Acceleration = Vector3.new(0, 48, 0),
				Drag = 4,
				WindAffectsDrag = true,
				Size = ns({{0, 6}, {0.3, 11}, {1, 12, 2}}),
				Transparency = ns({{0, 0}, {0.6, 0.2}, {1, 1}}),
				Color = cs({{0, hex("15181B")}, {0.5, hex("363A42")}, {1, hex("8C8680")}}),
				LightEmission = 0,
				LightInfluence = 1,
				Rotation = nr(0, 360),
				RotSpeed = nr(-30, 30),
			}},
			{name = "shock", class = "ParticleEmitter", offset = Vector3.new(0, -4.5, 0), dir = Vector3.new(1, 0, 0), emit = 7, props = {
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 0,
				Lifetime = nr(0.75, 0.85),
				Speed = nr(34, 42),
				SpreadAngle = Vector2.new(10, 180),
				Acceleration = Vector3.new(0, -3, 0),
				Drag = 0.8,
				WindAffectsDrag = true,
				Size = ns({{0, 4}, {1, 12}}),
				Transparency = ns({{0, 0.1}, {0.6, 0.3}, {1, 1}}),
				Color = cs({{0, hex("8C8680")}, {0.6, hex("8C8680")}, {1, hex("CFC8A6")}}),
				LightEmission = 0,
				LightInfluence = 1,
			}},
			{name = "chunks", class = "Debris", offset = Vector3.new(0, 1, 0), dir = Vector3.new(0, 1, 0), debris = {count = 4, size = Vector3.new(1.6, 0.5, 1.1), speed = {48, 62}, spread = 45, lifetime = 1.8, gravity_scale = 0.35, carry = 0.6, colours = {hex("7A4A26"), hex("363A42"), hex("C9953A")}, trail = "split_streak"}, props = {
			}},
			{name = "hotbits", class = "Debris", offset = Vector3.new(0, 1, 0), dir = Vector3.new(0, 1, 0), debris = {count = 4, size = Vector3.new(0.6, 0.35, 0.6), speed = {50, 70}, spread = 60, lifetime = 1.2, gravity_scale = 0.5, carry = 1, colours = {hex("FFD95E"), hex("FF7A22")}, trail = "split_streak"}, props = {
			}},
		},
	},
	torn_edge_smoke = {
		kind = "loop", priority = 2, anchor = "TornEdge", start = "on",
		use = "carriage split aftermath: thin mid-grey smoke along the kept half's torn end (roof edge and both wall tops from one box), a few orange embers and an ember glow; attach on the snap, fade out after ~20 s",
		layers = {
			{name = "smoulder", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 1, 0), part_size = Vector3.new(2.5, 3, 19), parent = "part", props = {
				Shape = Enum.ParticleEmitterShape.Box,
				ShapeStyle = Enum.ParticleEmitterShapeStyle.Volume,
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 14,
				Lifetime = nr(1.4, 1.8),
				Speed = nr(3, 5),
				SpreadAngle = Vector2.new(20, 20),
				Acceleration = Vector3.new(0, 11, 0),
				Drag = 0.2,
				WindAffectsDrag = true,
				Size = ns({{0, 1.5}, {1, 5}}),
				Transparency = ns({{0, 0}, {0.6, 0.1}, {1, 1}}),
				Color = cs({{0, hex("60645E")}, {1, hex("60645E")}}),
				LightEmission = 0,
				LightInfluence = 0.3,
				Rotation = nr(0, 360),
				RotSpeed = nr(-20, 20),
			}},
			{name = "embers", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 1, 0), part_size = Vector3.new(2.5, 3, 19), parent = "part", props = {
				Shape = Enum.ParticleEmitterShape.Box,
				ShapeStyle = Enum.ParticleEmitterShapeStyle.Volume,
				Texture = "rbxasset://textures/particles/sparkles_main.dds",
				Rate = 2,
				Lifetime = nr(0.8, 1.2),
				Speed = nr(3, 6),
				SpreadAngle = Vector2.new(25, 25),
				Acceleration = Vector3.new(0, 2, 0),
				Drag = 0.8,
				WindAffectsDrag = true,
				Size = ns({{0, 0.9}, {1, 0.4}}),
				Transparency = ns({{0, 0}, {0.7, 0.15}, {1, 1}}),
				Color = cs({{0, hex("FF7A22")}, {1, hex("FF7A22")}}),
				LightEmission = 1,
				LightInfluence = 0,
			}},
			{name = "glow", class = "PointLight", offset = Vector3.new(0, 0, 0), flicker = {min = 0.65, max = 1.05, hz = 4}, props = {
				Brightness = 2,
				Range = 10,
				Color = hex("FF7A22"),
				Shadows = false,
			}},
		},
	},
	topple_dust = {
		kind = "burst", priority = 1, anchor = "WreckDust", start = "off",
		use = "carriage split: long low cream dust cloud rolled out along a lost body's full length (30-stud box) when it lands after the topple (one per landing body)",
		layers = {
			{name = "dust", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 1, 0), part_size = Vector3.new(30, 3, 3), emit = 16, parent = "part", props = {
				Shape = Enum.ParticleEmitterShape.Box,
				ShapeStyle = Enum.ParticleEmitterShapeStyle.Volume,
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 0,
				Lifetime = nr(1.5, 1.7),
				Speed = nr(12, 16),
				SpreadAngle = Vector2.new(85, 85),
				Acceleration = Vector3.new(0, -2, 0),
				Drag = 3,
				WindAffectsDrag = true,
				Size = ns({{0, 6}, {0.25, 8}, {1, 8.5}}),
				Transparency = ns({{0, 0}, {0.6, 0.2}, {1, 1}}),
				Color = cs({{0, hex("CFC8A6")}, {1, hex("CFC8A6")}}),
				LightEmission = 0,
				LightInfluence = 1,
				Rotation = nr(0, 360),
				RotSpeed = nr(-15, 15),
			}},
		},
	},
	glass_split = {
		kind = "burst", priority = 1, anchor = "WindowPane", start = "off",
		use = "carriage split: the pane nearest the break on each wall smashes (mission variant of glass_burst: 23 bigger, longer-lived glinting shards on one emitter)",
		layers = {
			{name = "shards", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 0.3, 1), emit = 23, props = {
				Texture = "rbxasset://textures/particles/sparkles_main.dds",
				Rate = 0,
				Lifetime = nr(1.4, 1.8),
				Speed = nr(10, 18),
				SpreadAngle = Vector2.new(35, 35),
				Acceleration = Vector3.new(0, -25, 0),
				Drag = 1.2,
				WindAffectsDrag = true,
				Size = ns({{0, 0.7, 0.2}, {1, 0.7, 0.2}}),
				Transparency = ns({{0, 0}, {0.2, 0}, {0.24, 0.6}, {0.28, 0}, {0.5, 0}, {0.54, 0.6}, {0.58, 0}, {0.78, 0}, {0.82, 0.6}, {0.86, 0}, {0.94, 0.2}, {1, 1}}),
				Color = cs({{0, hex("FFFFFF")}, {1, hex("BFD9E6")}}),
				LightEmission = 0.8,
				LightInfluence = 0.3,
				Rotation = nr(0, 360),
				RotSpeed = nr(-400, 400),
			}},
		},
	},
}

return P
