-- generated by placefile.py audit: every colour and font the place file stores (for bible check)
local _ = Color3.fromRGB(42, 96, 64) -- x30 Color e.g. Workspace.Train.Coach0
local _ = Color3.fromRGB(246, 197, 0) -- x1 Color e.g. Workspace.Train.Buffer
local _ = Color3.fromRGB(255, 0, 255) -- x1 Color e.g. Workspace.PLACEHOLDER_Signal
