-- RR_Version (generated by rr-release-train; regenerate, do not edit). ModuleScript in ReplicatedStorage.
-- The Luau release tests and the smoke check read it to prove which build a server runs.
return {
	version = "0.4.0",
	channel = "alpha",
	built = "2026-09-28T03:31Z",
}
