-- RR_Analytics (ModuleScript, SERVER ONLY) - Risky Rails instrumentation over Roblox AnalyticsService.
-- Part of the rr-data-and-money skill. Place in ServerScriptService (or ServerStorage) with RR_AnalyticsPlan
-- (generated by track.py build from presets/tracking-plan.json; never edit the plan by hand).
--
--   local A = require(script.Parent.RR_Analytics)
--   A.init(require(script.Parent.RR_AnalyticsPlan), { store = { get = fn(player, key), set = fn(player, key, value) } })
--   A.onboarding(player, "picked_up_tool")                    -- each step once per player lifetime (store)
--   A.funnel(player, "trip", tripId, "departed")               -- recurring funnel step
--   A.source(player, 1250, newBalance, "Gameplay", "fare_bank", { difficulty = "Hard" })
--   A.sink(player, 40, newBalance, "Shop", "coal", { difficulty = "Easy" })
--   A.progress(player, "trip", "Complete", 3, nil, { crew = 4, reason = "arrived" })
--   A.event(player, "lever_pulled", 3.2, { choice = "risky", time_left = 3.2, crew = 4 })
--   local arm = A.expose(player, "example_onboarding_hint")    -- deterministic arm + one exposure event
--
-- Rules it enforces: only planned ids are sent (unknown ids are dropped with one warning each); enum fields
-- outside their list become "other"; numeric fields become bucket labels; amounts must be finite and > 0;
-- per-player and per-server rate limits (20 x players per server; platform 120 + 20 x CCU); every AnalyticsService call
-- is pcall-wrapped so analytics can never break gameplay.
-- In Studio (or opts.debug) calls are printed, not sent. Written in the Lua 5.1 subset so it is tested in a VM.

local A = {}

local plan, opts, svc = nil, {}, nil
local sent, dropped, errors, limited, coerced = 0, 0, 0, 0, 0
local warned, onb, exposed, buckets = {}, {}, {}, {}
local FIELD_KEYS = { "CustomField01", "CustomField02", "CustomField03" }

local function warnOnce(key, msg)
	if not warned[key] then
		warned[key] = true
		warn("[RR_Analytics] " .. msg)
	end
end

local function now()
	if opts.clock then
		return opts.clock()
	end
	if time then
		return time()
	end
	return os.time()
end

local function enumItem(enumType, item)
	local ok, v = pcall(function()
		return Enum[enumType][item]
	end)
	if ok then
		return v
	end
	return nil
end

local function fieldKey(i)
	local item = enumItem("AnalyticsCustomFieldKeys", FIELD_KEYS[i])
	if item then
		return item.Name
	end
	return FIELD_KEYS[i]
end

local function isFinite(x)
	return type(x) == "number" and x == x and x ~= math.huge and x ~= -math.huge
end

local function bucketLabel(edges, x)
	if not isFinite(x) then
		return "other"
	end
	if x < edges[1] then
		return "<" .. tostring(edges[1])
	end
	for i = 1, #edges - 1 do
		if x < edges[i + 1] then
			return tostring(edges[i]) .. "-" .. tostring(edges[i + 1])
		end
	end
	return tostring(edges[#edges]) .. "+"
end

-- plan field specs + caller values -> { CustomField01 = "..." } ; extra = { slot, value } for experiment tags
local function buildFields(specs, values, tagValue)
	local out, used = {}, 0
	values = values or {}
	for i, spec in ipairs(specs or {}) do
		local v = values[spec.name]
		local s
		if v == nil then
			s = "none"
		elseif spec.enum then
			s = tostring(v)
			local ok = false
			for _, e in ipairs(spec.enum) do
				if e == s then
					ok = true
				end
			end
			if not ok then
				coerced = coerced + 1
				s = "other"
			end
		elseif spec.buckets then
			s = bucketLabel(spec.buckets, tonumber(v))
		else
			s = "other"
		end
		out[fieldKey(i)] = s
		used = i
	end
	if tagValue and used < 3 then
		out[fieldKey(used + 1)] = tagValue
	end
	return out
end

local function allow(player, key, perMin)
	perMin = perMin or (plan.budgets and plan.budgets.max_per_min_default) or 20
	local id = tostring(player.UserId) .. "|" .. key
	local b = buckets[id]
	local t = now()
	if not b then
		b = { tokens = perMin, at = t }
		buckets[id] = b
	end
	b.tokens = math.min(perMin, b.tokens + (t - b.at) * perMin / 60)
	b.at = t
	if b.tokens < 1 then
		limited = limited + 1
		return false
	end
	b.tokens = b.tokens - 1
	return true
end

-- Roblox documents 120 + 20 x CCU AnalyticsService requests per minute without saying whether that is per server
-- or experience-wide. Each server spends at most 20 x its players (+ opts.serverExtra, default 0), which sums to
-- 20 x CCU across all servers and so stays inside the limit under either reading, however many small servers run.
local global = {}
local function allowGlobal()
	local n = 1
	if opts.playerCount then
		n = opts.playerCount()
	else
		pcall(function()
			n = #game:GetService("Players"):GetPlayers()
		end)
	end
	local perMin = 20 * math.max(1, n) + (opts.serverExtra or 0)
	local t = now()
	if not global.at then
		global.tokens, global.at = perMin, t
	end
	global.tokens = math.min(perMin, global.tokens + (t - global.at) * perMin / 60)
	global.at = t
	if global.tokens < 1 then
		limited = limited + 1
		return false
	end
	global.tokens = global.tokens - 1
	return true
end

local function send(method, ...)
	if opts.debug then
		local parts = {}
		for i = 1, select("#", ...) do
			local v = select(i, ...)
			if type(v) == "table" and not v.UserId then
				local kv = {}
				for k, x in pairs(v) do
					table.insert(kv, tostring(k) .. "=" .. tostring(x))
				end
				table.sort(kv)
				v = "{" .. table.concat(kv, ",") .. "}"
			elseif type(v) == "table" then
				v = "player " .. tostring(v.UserId)
			end
			table.insert(parts, tostring(v))
		end
		print("[RR_Analytics] " .. method .. " " .. table.concat(parts, " "))
		sent = sent + 1
		return true
	end
	local fn = svc and svc[method]
	if not fn then
		errors = errors + 1
		warnOnce("missing:" .. method, "AnalyticsService." .. method .. " unavailable")
		return false
	end
	local ok, err = pcall(fn, svc, ...)
	if ok then
		sent = sent + 1
	else
		errors = errors + 1
		warnOnce("err:" .. method, method .. " failed: " .. tostring(err))
	end
	return ok
end

local function call(method, ...)
	if not allowGlobal() then
		return false
	end
	return send(method, ...)
end

local function drop(key, msg)
	dropped = dropped + 1
	warnOnce(key, msg)
	return false
end

local function stepIndex(steps, id)
	for i, s in ipairs(steps) do
		if s.id == id then
			return i, s
		end
	end
	return nil
end

-- experiments ------------------------------------------------------------------------------------------
-- djb2 over "salt:userId" modulo 2^32 (exact in doubles); identical to abtest.py assign.
local function hash(s)
	local h = 5381
	for i = 1, #s do
		h = (h * 33 + string.byte(s, i)) % 4294967296
	end
	return h
end

local function armFor(exp, userId)
	local b = hash(exp.salt .. ":" .. tostring(userId)) % 10000
	local total = 0
	for _, w in ipairs(exp.weights) do
		total = total + w
	end
	local acc = 0
	for i, w in ipairs(exp.weights) do
		acc = acc + w
		if b < acc / total * 10000 then
			return exp.arms[i]
		end
	end
	return exp.arms[#exp.arms]
end
A._hash, A._armFor = hash, armFor

function A.arm(player, expId)
	local exp = plan and plan.experiments[expId]
	if not exp or not exp.active then
		return nil
	end
	return armFor(exp, player.UserId)
end

local function tagFor(player, target)
	for expId, exp in pairs(plan.experiments) do
		if exp.active and exp.tag then
			for _, t in ipairs(exp.tag) do
				if t == target then
					return expId .. ":" .. armFor(exp, player.UserId)
				end
			end
		end
	end
	return nil
end

function A.expose(player, expId)
	local exp = plan and plan.experiments[expId]
	if not exp then
		return drop("exp:" .. tostring(expId), "unknown experiment " .. tostring(expId))
	end
	if not exp.active then
		return nil
	end
	local arm = armFor(exp, player.UserId)
	local key = tostring(player.UserId) .. "|" .. expId
	if not exposed[key] then
		exposed[key] = true
		call("LogCustomEvent", player, "exp_exposure", 1, buildFields(
			{ { name = "experiment", enum = { expId } }, { name = "arm", enum = exp.arms } },
			{ experiment = expId, arm = arm }))
	end
	return arm
end

-- logging API ----------------------------------------------------------------------------------------
function A.onboarding(player, stepId, values)
	if not plan then
		return drop("noinit", "init() not called")
	end
	local i, step = stepIndex(plan.onboarding, stepId)
	if not i then
		return drop("onb:" .. tostring(stepId), "unknown onboarding step " .. tostring(stepId))
	end
	local uid = player.UserId
	local done = onb[uid]
	if not done then
		done = {}
		if opts.store and opts.store.get then
			local ok, saved = pcall(opts.store.get, player, "rr_onboarding")
			if ok and type(saved) == "table" then
				for _, s in ipairs(saved) do
					done[s] = true
				end
			end
		end
		onb[uid] = done
	end
	if done[stepId] or not allowGlobal() then
		return false
	end
	done[stepId] = true
	if opts.store and opts.store.set then
		local list = {}
		for k in pairs(done) do
			table.insert(list, k)
		end
		table.sort(list)
		pcall(opts.store.set, player, "rr_onboarding", list)
	end
	return send("LogOnboardingFunnelStepEvent", player, i, step.name,
		buildFields(nil, values, tagFor(player, "onboarding")))
end

function A.funnel(player, funnelId, sessionId, stepId, values)
	local f = plan and plan.funnels[funnelId]
	if not f then
		return drop("fun:" .. tostring(funnelId), "unknown funnel " .. tostring(funnelId))
	end
	local i, step = stepIndex(f.steps, stepId)
	if not i then
		return drop("fun:" .. funnelId .. ":" .. tostring(stepId), "unknown step " .. tostring(stepId) .. " in " .. funnelId)
	end
	if not allow(player, "funnel:" .. funnelId, 30) then
		return false
	end
	return call("LogFunnelStepEvent", player, funnelId, tostring(sessionId), i, step.name,
		buildFields(nil, values, tagFor(player, funnelId)))
end

local function economy(flow, player, amount, balance, txType, sku, values)
	local e = plan and plan.economy
	if not e then
		return drop("noinit", "init() not called")
	end
	if not isFinite(amount) or amount <= 0 or not isFinite(balance) or balance < 0 then
		return drop("econ:num", "economy event with a bad amount or balance (must be finite, amount > 0)")
	end
	if not e.types[txType] then
		return drop("econ:type:" .. tostring(txType), "unplanned transaction type " .. tostring(txType))
	end
	local skus = flow == "Source" and e.sources or e.sinks
	if not skus[sku] then
		return drop("econ:sku:" .. tostring(sku), "unplanned " .. flow .. " sku " .. tostring(sku))
	end
	if not allow(player, "economy", 30) then
		return false
	end
	local flowItem = enumItem("AnalyticsEconomyFlowType", flow) or flow
	local typeItem = enumItem("AnalyticsEconomyTransactionType", txType)
	return call("LogEconomyEvent", player, flowItem, plan.currency, amount, balance,
		typeItem and typeItem.Name or txType, sku, buildFields(e.fields, values, tagFor(player, "economy")))
end

function A.source(player, amount, balance, txType, sku, values)
	return economy("Source", player, amount, balance, txType, sku, values)
end

function A.sink(player, amount, balance, txType, sku, values)
	return economy("Sink", player, amount, balance, txType, sku, values)
end

function A.progress(player, pathId, status, level, levelName, values)
	local p = plan and plan.progression[pathId]
	if not p then
		return drop("prog:" .. tostring(pathId), "unknown progression path " .. tostring(pathId))
	end
	if status ~= "Start" and status ~= "Complete" and status ~= "Fail" then
		return drop("prog:status", "progression status must be Start, Complete or Fail")
	end
	if type(level) ~= "number" or level < 1 or level > #p.levels then
		return drop("prog:level:" .. pathId, "progression level out of range for " .. pathId)
	end
	if not allow(player, "prog:" .. pathId, 20) then
		return false
	end
	local statusItem = enumItem("AnalyticsProgressionType", status) or status
	return call("LogProgressionEvent", player, pathId, statusItem, level, levelName or p.levels[level],
		buildFields(p.fields, values, tagFor(player, pathId)))
end

function A.event(player, eventId, value, values)
	local ev = plan and plan.events[eventId]
	if not ev then
		return drop("ev:" .. tostring(eventId), "unplanned custom event " .. tostring(eventId))
	end
	if value ~= nil and not isFinite(value) then
		value = nil
	end
	if not allow(player, "ev:" .. eventId, ev.max_per_min) then
		return false
	end
	return call("LogCustomEvent", player, eventId, value or 1, buildFields(ev.fields, values, tagFor(player, eventId)))
end

-- index of a level name in a progression path (nil when the plan does not define it)
function A.levelIndex(pathId, levelName)
	local p = plan and plan.progression[pathId]
	if not p then
		return nil
	end
	for i, name in ipairs(p.levels) do
		if name == levelName then
			return i
		end
	end
	return nil
end

function A.stats()
	return { sent = sent, dropped = dropped, errors = errors, limited = limited, coerced = coerced }
end

function A.forget(player)
	local uid = player.UserId
	onb[uid] = nil
	local prefix = tostring(uid) .. "|"
	for k in pairs(buckets) do
		if string.sub(k, 1, #prefix) == prefix then
			buckets[k] = nil
		end
	end
	for k in pairs(exposed) do
		if string.sub(k, 1, #prefix) == prefix then
			exposed[k] = nil
		end
	end
end

function A.init(thePlan, options)
	plan = thePlan
	opts = options or {}
	if opts.debug == nil then
		local ok, isStudio = pcall(function()
			return game:GetService("RunService"):IsStudio()
		end)
		opts.debug = ok and isStudio or false
	end
	svc = opts.service
	if not svc then
		local ok, s = pcall(function()
			return game:GetService("AnalyticsService")
		end)
		svc = ok and s or nil
	end
	if not opts.noAutoForget then
		pcall(function()
			game:GetService("Players").PlayerRemoving:Connect(A.forget)
		end)
	end
	return A
end

return A
