-- RR_AnalyticsPlan (ModuleScript) - GENERATED by rr-data-and-money track.py from tracking-plan.json.
-- Do not edit: change the plan and run `track.py build`. Required by RR_Analytics.init().
return {
	version = "2026-09-28b",
	currency = "Coins",
	budgets = { max_per_min_default = 20 },
	onboarding = {
		{ id = "join", name = "Joined" },
		{ id = "picked_up_tool", name = "Picked up tool" },
		{ id = "shovelled_coal", name = "Shovelled coal" },
		{ id = "pulled_lever", name = "Pulled lever" },
		{ id = "first_bank", name = "First bank" },
		{ id = "run_end", name = "Run end" },
	},
	funnels = {
		trip = {
			steps = {
				{ id = "queued", name = "Queued" },
				{ id = "boarded", name = "Boarded" },
				{ id = "departed", name = "Departed" },
				{ id = "first_fork", name = "First fork" },
				{ id = "first_bank", name = "First bank" },
				{ id = "arrived", name = "Arrived" },
			},
		},
		supply = {
			steps = {
				{ id = "opened", name = "Terminal opened" },
				{ id = "ordered", name = "Order placed" },
				{ id = "fetched", name = "Crate fetched" },
			},
		},
		purchase = {
			steps = {
				{ id = "prompt_shown", name = "Prompt shown" },
				{ id = "accepted", name = "Accepted" },
				{ id = "granted", name = "Granted" },
			},
		},
	},
	economy = {
		types = {
			Gameplay = true,
			Shop = true,
			IAP = true,
			ContextualPurchase = true,
			TimedReward = true,
			Onboarding = true,
			Promo = true,
		},
		sources = {
			fare_bank = true,
			fare_pack_s = true,
			fare_pack_m = true,
			fare_pack_l = true,
			promo_code = true,
		},
		sinks = {
			coal = true,
			toolbox = true,
			sandwich = true,
			medkit = true,
			recovery_fee = true,
			loco_2 = true,
			loco_3 = true,
			loco_4 = true,
			loco_5 = true,
			line_2 = true,
			livery = true,
		},
		fields = {
			{ name = "difficulty", enum = { "Easy", "Medium", "Hard", "Insane", "Lobby" } },
		},
	},
	progression = {
		trip = {
			levels = { "Easy", "Medium", "Hard", "Insane" },
			fields = {
				{ name = "crew", buckets = { 2, 3, 5 } },
				{ name = "reason", enum = { "arrived", "boiler_explosion", "passengers_dead", "stall", "buffer_overrun", "abandoned" } },
			},
		},
		locomotives = { levels = { "loco_2", "loco_3", "loco_4", "loco_5" }, fields = {  } },
		lines = { levels = { "line_2" }, fields = {  } },
	},
	events = {
		lever_pulled = {
			fields = {
				{ name = "choice", enum = { "safe", "risky", "none" } },
				{ name = "time_left", buckets = { 2, 5, 8 } },
				{ name = "crew", buckets = { 2, 3, 5 } },
			},
			max_per_min = 12,
		},
		run_end = {
			fields = {
				{ name = "reason", enum = { "arrived", "boiler_explosion", "passengers_dead", "stall", "buffer_overrun", "abandoned" } },
				{ name = "difficulty", enum = { "Easy", "Medium", "Hard", "Insane" } },
				{ name = "crew", buckets = { 2, 3, 5 } },
			},
			max_per_min = 4,
		},
		player_left = {
			fields = {
				{ name = "phase", enum = { "lobby", "queue", "boarding", "run", "results" } },
				{ name = "difficulty", enum = { "Easy", "Medium", "Hard", "Insane", "Lobby" } },
			},
			max_per_min = 2,
		},
		crisis_end = {
			fields = {
				{ name = "kind", enum = { "coal_low", "pressure_high", "breakdown", "passengers" } },
				{ name = "outcome", enum = { "fixed", "failed", "expired" } },
				{ name = "crew", buckets = { 2, 3, 5 } },
			},
			max_per_min = 20,
		},
		results_action = {
			fields = {
				{ name = "action", enum = { "requeue", "invite", "share", "leave", "idle_home" } },
			},
			max_per_min = 6,
		},
		crate_resolved = {
			fields = {
				{ name = "kind", enum = { "coal", "toolbox", "sandwich", "medkit" } },
				{ name = "outcome", enum = { "fetched", "slid_off" } },
				{ name = "difficulty", enum = { "Easy", "Medium", "Hard", "Insane" } },
			},
			max_per_min = 6,
		},
	},
	experiments = {
		example_onboarding_hint = {
			arms = { "A", "B" },
			weights = { 50, 50 },
			salt = "obh-2026-10",
			active = false,
			tag = { "onboarding" },
		},
	},
}
