-- RR_Version (generated by rr-release-train; regenerate, do not edit). ModuleScript in ReplicatedStorage.
-- The Luau release tests and the smoke check read it to prove which build a server runs.
return {
	version = "0.1.0-alpha.1",
	channel = "alpha",
	built = "2026-09-28T03:25Z",
}
