--[[
TrainSplitConfig  (ModuleScript in ReplicatedStorage)

Every tunable for the carriage split lives here; the server (TrainSplit) and every client
(TrainSplitClient) read the same table, so change numbers here only.
Numbers marked "break_spec" come from src/kit/break_spec.json (mission 260929-train-splits, T0).

Break frame B (per carriage, saved by RR_TrainSplit_Setup in Train/RR_Breaks/BreakN.BreakCFrame):
origin on the carriage centre line, at floor-top height, on the break plane.
+X across the carriage (right when facing the front), +Y up, +Z toward the REAR of the train.
]]

local Config = {}

Config.Version = "2.1.0"
Config.RemoteName = "RR_TrainSplitFX" -- RemoteEvent in ReplicatedStorage, server -> clients only
Config.WreckFolderName = "RR_Wrecks" -- workspace folder the lost bodies move into

-- Motion. The train never moves: the world scrolls past it at the train's speed.
Config.SpeedAttribute = "Speed" -- attribute on the train Model, studs/s (your game keeps it current)
Config.SpeedDefault = 35 -- canon gameplay.speed.normal; used when the attribute is missing or not a number
Config.MaxSpeed = 60 -- the Speed attribute is clamped to 0..MaxSpeed (canon fast is 50); NaN/inf use the default
Config.Brake = 12 -- break_spec motion.brake: studs/s^2 the lost part slows by until it moves with the terrain
Config.Recoil = { dist = 0.8, time = 0.2 } -- break_spec motion.recoil: the blast shoves the wreck back
Config.LeadTime = 0.25 -- the snap happens this long after SplitAt, so metal_tear (t = -0.25) lands on the boom
Config.LateTolerance = 0.5 -- a client that learns of the snap later than this skips the one-shot fx
Config.Despawn = { distance = 700, time = 30 } -- break_spec: studs behind where it broke off / seconds
Config.RiderConfirmDelay = 1.0 -- TrainSplit.ConfirmRiders re-checks the rider candidates this long after the snap
Config.MisuseAttribute = "RR_RemoteMisuse" -- set on a Player who fires the server -> client remote (flagged once)

-- Topple (break_spec topple). One entry per lost body, front-most first; a snap uses one side for all.
-- roll in degrees onto its side, bounce = {lowest, rest}, yaw = twist in degrees, sink = studs into the ground.
Config.Side = "random" -- "random" (seeded per snap) | "left" | "right" (as seen facing the front)
-- TOPPLE BEGIN (break_spec.json v2.1.0; generated by tests/sync_spec.luau)
Config.Pivot = { X_abs = 11.7, Y = -8.6 } -- outer bogie edge at rail level on the falling side
Config.Topple = {
	-- the broken half (front-most lost body)
	{ delay = 0.45, roll = 95.0, roll_time = 1.05, ease = "QuadIn", bounce = { 90.0, 95.0 }, bounce_time = 0.35, yaw = 7.0, sink = 0.4 },
	-- a whole carriage dragged behind it (break 1 only: carriage 2)
	{ delay = 0.8, roll = 95.0, roll_time = 1.2, ease = "QuadIn", bounce = { 91.0, 95.0 }, bounce_time = 0.4, yaw = -4.0, sink = 0.35 },
}
-- TOPPLE END

-- The jagged tear, {X0, X1, Y0, Y1, d, region}: inside the cell the tear sits at Z = d.
-- Same numbers as RR_TrainSplit_Setup; the runtime uses them to tell riders from people on the kept half.
-- CELLS BEGIN (break_spec.json v2.1.0, 29 cells; generated by tests/sync_spec.luau)
Config.Cells = {
	{ -14.0, -7.1, -12.0, 0.6, 0.6, "floor" },
	{ -7.1, -2.8, -12.0, 0.6, 2.4, "floor" },
	{ -2.8, 0.6, -12.0, 0.6, 0.9, "floor" },
	{ 0.6, 4.1, -12.0, 0.6, 3.6, "floor" },
	{ 4.1, 7.1, -12.0, 0.6, 1.5, "floor" },
	{ 7.1, 14.0, -12.0, 0.6, -0.3, "floor" },
	{ -14.0, -7.1, 0.6, 1.5, 0.7, "wall_W" },
	{ 7.1, 14.0, 0.6, 1.5, -0.6, "wall_E" },
	{ -14.0, -7.1, 1.5, 3.3, -0.4, "wall_W" },
	{ 7.1, 14.0, 1.5, 3.3, 0.5, "wall_E" },
	{ -14.0, -7.1, 3.3, 5.7, 0.9, "wall_W" },
	{ 7.1, 14.0, 3.3, 5.7, -0.2, "wall_E" },
	{ -14.0, -7.1, 5.7, 7.4, 0.1, "wall_W" },
	{ 7.1, 14.0, 5.7, 7.4, 0.8, "wall_E" },
	{ -14.0, -7.1, 7.4, 8.95, -0.8, "wall_W" },
	{ 7.1, 14.0, 7.4, 8.95, -0.5, "wall_E" },
	{ -14.0, -7.1, 8.95, 11.18, 0.4, "wall_W" },
	{ 7.1, 14.0, 8.95, 11.18, 0.2, "wall_E" },
	{ -7.1, 7.1, 0.6, 8.95, 0.2, "mid" },
	{ -7.1, -2.5, 8.95, 11.18, 0.3, "mid_pelmet" },
	{ -2.5, 2.5, 8.95, 11.18, -0.5, "mid_pelmet" },
	{ 2.5, 7.1, 8.95, 11.18, 0.25, "mid_pelmet" },
	{ -14.0, -7.1, 11.18, 18.0, 0.3, "roof" },
	{ -7.1, -4.6, 11.18, 18.0, -1.6, "roof" },
	{ -4.6, -1.9, 11.18, 18.0, -3.9, "roof" },
	{ -1.9, 0.9, 11.18, 18.0, -2.4, "roof" },
	{ 0.9, 3.7, 11.18, 18.0, -4.8, "roof" },
	{ 3.7, 7.1, 11.18, 18.0, -1.1, "roof" },
	{ 7.1, 14.0, 11.18, 18.0, 0.1, "roof" },
}
-- CELLS END

-- Timeline (break_spec events). t = seconds after the snap. fx = key into Config.FX, sound = key into
-- Config.Sounds, at = key into Config.Anchors, or "impact" (where each body lands) / "wreck" (a body's root).
-- soundAt overrides where the sound plays. loop = seconds a looping fx runs, fade = its fade-out after that.
Config.Events = {
	{ t = -0.25, id = "metal_tear", sound = "metal_tear", at = "split_core" },
	{ t = 0.0, id = "split_explosion", fx = "split_explosion", sound = "split_explosion", shake = "big", at = "split_core" },
	{ t = 0.0, id = "glass_burst", fx = "glass_burst", sound = "split_glass", at = "glass" },
	{ t = 0.05, id = "torn_edge_smoke", fx = "torn_edge_smoke", loop = 20, fade = 3.5, at = "torn_edge" },
	{ t = 0.3, t_end = "stop", id = "wreck_scrape", sound = "wreck_scrape", at = "wreck" },
	{ t = 0.8, id = "debris_rain", sound = "debris_rain", at = "debris" },
	{ t = "impact", id = "topple_crash", fx = "topple_dust", sound = "topple_crash", shake = "medium", at = "impact", soundAt = "wreck" },
}

-- Anchor points in the break frame (studs). RR_VFX anchors are Attachments turned X forward, Y up, Z right:
-- CFrame = BreakCF * CFrame.new(p) * CFrame.Angles(0, rad(yaw), 0), yaw 90 unless given.
Config.Anchors = {
	split_core = Vector3.new(0, 5, 0), -- SplitCore: split_explosion burst; the "break" sound emitter (metal_tear)
	debris = Vector3.new(0, 3, 2), -- break_spec events: debris_rain
	glass = { -- SplitGlassL/R: outer face of the kept half's window pane nearest the break, Z pointing out
		{ p = Vector3.new(-9.75, 6.6, -4.5), yaw = -90 },
		{ p = Vector3.new(9.75, 6.6, -4.5), yaw = 90 },
	},
	torn_edge = Vector3.new(0, 12.4, -2.4), -- TornEdge: torn_edge_smoke on the kept half, on the roof tooth (Z = its d)
	-- WreckDust (topple_dust) is placed per body where it lands: (+-Pivot.X_abs, Pivot.Y, body mid-length)
}

-- FX presets (T3, src/fx/build/RR_FXPresets.lua), played through RR_VFX (ReplicatedStorage.RR_VFX or
-- ReplicatedStorage.RRFX.RR_VFX): VFX.burst for one-shots, VFX.attach + setIntensity/detach for the loop.
-- A missing RR_VFX or a failing preset falls back to Config.FallbackFX below.
Config.FX = {
	split_explosion = "split_explosion", -- burst, SplitCore
	glass_burst = "glass_burst", -- burst, SplitGlassL/R
	torn_edge_smoke = "torn_edge_smoke", -- loop, TornEdge
	topple_dust = "topple_dust", -- burst, WreckDust
}
Config.FxAnchorLife = 12 -- seconds a one-shot fx anchor lives: longer than any preset's particles

-- Sounds: made from code by the T4 pass (rr-soundsmith), licence-clean, files in src/sound/final/.
-- Upload each rr_split_<id>.wav (Studio Asset Manager or Creator Hub) and paste "rbxassetid://<id>".
-- An empty SoundId is skipped. Numbers are from src/sound/final/SOUNDS.md (mix boom > tear > crash > debris).
-- Group = SoundGroup name in SoundService, used when it exists. Pitch = random PlaybackSpeed range per play.
Config.Sounds = {
	-- rr_split_metal_tear.wav, t -0.25: the snap is 0.25 s into the file, so it lands on the boom
	metal_tear = { SoundId = "", Volume = 0.594, Is3D = true, RollOffMinDistance = 16, RollOffMaxDistance = 240, Group = "Alarms", Pitch = { 0.97, 1.03 } },
	-- rr_split_split_explosion.wav, t 0: positional layer at the break plus a flat train-wide layer (Volume2D)
	split_explosion = { SoundId = "", Volume = 0.5, Volume2D = 0.792, Is3D = true, RollOffMinDistance = 16, RollOffMaxDistance = 240, Group = "Alarms", Pitch = { 0.96, 1.04 } },
	-- rr_split_split_glass.wav (same audio as glass_smash: one upload serves both), t 0, once per side 0.1 s apart
	split_glass = { SoundId = "", Volume = 0.562, Is3D = true, RollOffMinDistance = 16, RollOffMaxDistance = 240, Group = "Alarms", Pitch = { 0.93, 1.07 }, Stagger = 0.1 },
	-- rr_split_debris_rain.wav, t 0.8
	debris_rain = { SoundId = "", Volume = 0.397, Is3D = true, RollOffMinDistance = 10, RollOffMaxDistance = 140, Group = "Actions", Pitch = { 0.9, 1.1 } },
	-- rr_split_topple_crash.wav, each landing (break 1: carriage 2 lands 0.5 s later, a bigger body pitched 0.94)
	topple_crash = { SoundId = "", Volume = 0.561, Is3D = true, RollOffMinDistance = 16, RollOffMaxDistance = 240, Group = "Actions", Pitch = { 0.92, 1.06 }, BodyPitch = { 1, 0.94 } },
	-- rr_split_wreck_scrape.wav, from t 0.3 on the front-most wreck. Authored 2.7 s for Speed 35: its playback
	-- speed and fade-out now follow Config.Scrape (S2-4); Length and FitSpeed are no longer read.
	wreck_scrape = { SoundId = "", Volume = 0.398, Is3D = true, RollOffMinDistance = 10, RollOffMaxDistance = 140, Group = "Actions", Pitch = { 0.95, 1.05 }, Length = 2.7, FitSpeed = { 0.8, 1.25 } },
}

-- wreck_scrape playback (sound critic S2-4): authored for Speed 35, so it plays at RefSpeed / V (clamped to
-- PlaybackRange) and fades out over Fade seconds once the wreck's speed over the ground (TrainSplitShared,
-- not measured) drops under StopBelow studs/s.
Config.Scrape = { RefSpeed = 35, PlaybackRange = { 0.7, 1.2 }, StopBelow = 2, Fade = 0.3 }

-- Camera shake (client). amplitude in degrees, fading to 0 at `falloff` studs from the camera.
Config.ReduceMotionAttribute = "ReduceMotion" -- Player attribute; true = no camera shake (your settings menu sets it)
Config.Shake = {
	big = { amplitude = 1.5, duration = 0.9, frequency = 14, falloff = 250 },
	medium = { amplitude = 0.6, duration = 0.5, frequency = 12, falloff = 150 },
}

-- Built-in fallback emitters, only when RR_VFX or a preset is missing. Built-in textures, phone-sized counts.
-- Lists are evenly spaced keypoints over a particle's life; colours are hex (canon soot/ironwork/brass/hazard).
local TEX_FIRE = "rbxasset://textures/particles/fire_main.dds"
local TEX_SMOKE = "rbxasset://textures/particles/smoke_main.dds"
local TEX_SPARK = "rbxasset://textures/particles/sparkles_main.dds"
Config.SmokeWind = 18 -- studs/s^2 pushing fallback smoke toward the rear: the air streams past the moving train
Config.FallbackFX = {
	split_explosion = {
		explosion = true, -- Roblox's built-in Explosion look (no pressure, breaks no joints)
		flash = { Brightness = 4, Range = 40, Color = "#FFC46B", Time = 0.12 }, -- one short flash (flash-safe)
		life = 3.5,
		emitters = {
			{ Texture = TEX_FIRE, Count = 30, Lifetime = { 0.35, 0.8 }, Speed = { 18, 36 }, Size = { 5, 11, 2 }, Transparency = { 0, 0.2, 1 }, Color = { "#FFE39A", "#FF7A1A", "#7A2E0B" }, LightEmission = 0.8, Drag = 5 },
			{ Texture = TEX_SMOKE, Count = 22, Lifetime = { 1.6, 3.2 }, Speed = { 6, 14 }, Size = { 6, 16, 22 }, Transparency = { 0.15, 0.5, 1 }, Color = { "#363A42", "#15181B" }, Drag = 2, Wind = true },
			{ Texture = TEX_SPARK, Count = 36, Lifetime = { 0.5, 1.1 }, Speed = { 30, 60 }, Size = { 0.5, 0.1 }, Transparency = { 0, 1 }, Color = { "#FFD27A", "#F2C230" }, LightEmission = 1, Drag = 1, Acceleration = { 0, -60, 0 } },
		},
	},
	glass_burst = {
		life = 1.2,
		emitters = {
			{ Texture = TEX_SPARK, Count = 14, Lifetime = { 0.4, 0.9 }, Speed = { 12, 24 }, Size = { 0.35, 0.1 }, Transparency = { 0, 1 }, Color = { "#E8F4FF", "#BFD8EE" }, LightEmission = 0.4, Acceleration = { 0, -50, 0 } },
		},
	},
	torn_edge_smoke = {
		loop = true,
		life = 3.5,
		emitters = {
			{ Texture = TEX_SMOKE, Rate = 6, Lifetime = { 2, 3.5 }, Speed = { 1, 3 }, Size = { 1.5, 5 }, Transparency = { 0.35, 1 }, Color = { "#4A4E55", "#15181B" }, Drag = 1, Wind = true },
		},
	},
	topple_dust = {
		life = 3,
		emitters = {
			{ Texture = TEX_SMOKE, Count = 28, Lifetime = { 1.4, 2.8 }, Speed = { 8, 16 }, Size = { 4, 10, 14 }, Transparency = { 0.2, 0.6, 1 }, Color = { "#8C7A60", "#5E5241" }, Drag = 3, Spread = 75 },
		},
	},
}

return Config
