-- RR_FXPresets: GENERATED by rr-vfx-lighting (vfx.py build, 2026-09-28) from presets/vfx.json.
-- Do not edit: change the JSON and rebuild. Palette colours use hex(); light levels use lvl() (intensities, not palette).
local function hex(h) return Color3.fromHex(h) end
local function lvl(r, g, b) return Color3.fromRGB(r, g, b) end

local function nr(a, b) return NumberRange.new(a, b) end
local function ns(t)
	local k = {}
	for i, p in ipairs(t) do k[i] = NumberSequenceKeypoint.new(p[1], p[2], p[3] or 0) end
	return NumberSequence.new(k)
end
local function cs(t)
	local k = {}
	for i, p in ipairs(t) do k[i] = ColorSequenceKeypoint.new(p[1], p[2]) end
	return ColorSequence.new(k)
end

local P = {}

P.meta = {
	speed_max = 50, -- gameplay.speed.fast (rr-bible)
	speeds = {slow = 20, normal = 35, fast = 50},
	wind_scale = 1,
	budget_status = "assumed (OQ-029 default A): not canon until the owner decides; re-measure at the alpha live check (tech.streaming.live_check)",
	tiers = {
		phone = {rate_scale = {[1] = 1, [2] = 0.7, [3] = 0.5}, post_off = {"BloomEffect", "SunRaysEffect", "DepthOfFieldEffect"}, live_particles = 400, burst_peak = 800},
		pc = {rate_scale = {[1] = 1, [2] = 1, [3] = 1}, post_off = {"DepthOfFieldEffect"}, live_particles = 1500, burst_peak = 2500},
	},
}

P.trails = {
	debris_smoke = {width = 0.9, props = {
		Lifetime = 0.6,
		MinLength = 0.1,
		FaceCamera = true,
		WidthScale = ns({{0, 1}, {1, 0.25}}),
		Transparency = ns({{0, 0.25}, {1, 1}}),
		Color = cs({{0, hex("15181B")}, {1, hex("8C8680")}}),
		LightEmission = 0,
		LightInfluence = 1,
	}},
	debris_spark = {width = 0.35, props = {
		Lifetime = 0.25,
		MinLength = 0.05,
		FaceCamera = true,
		WidthScale = ns({{0, 1}, {1, 0.1}}),
		Transparency = ns({{0, 0}, {1, 1}}),
		Color = cs({{0, hex("FFD95E")}, {1, hex("FF7A22")}}),
		LightEmission = 1,
		LightInfluence = 0,
	}},
}

P.presets = {
	steam_chimney = {
		kind = "loop", priority = 2, anchor = "Chimney", start = "on",
		use = "chimney steam; rate follows Speed (idle to gameplay.speed.fast)",
		speed_link = {layers = {"plume"}, idle = 5, max = 18},
		layers = {
			{name = "plume", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 1, 0), props = {
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 18,
				Lifetime = nr(2.4, 3.2),
				Speed = nr(7, 10),
				SpreadAngle = Vector2.new(8, 8),
				Acceleration = Vector3.new(0, 3, 0),
				Drag = 1.2,
				WindAffectsDrag = true,
				Size = ns({{0, 2.6}, {0.3, 7.5}, {1, 12, 1.5}}),
				Transparency = ns({{0, 0.15}, {0.6, 0.35}, {1, 1}}),
				Color = cs({{0, hex("FFFFFF")}, {1, hex("D9D8D2")}}),
				LightEmission = 0.05,
				LightInfluence = 0.9,
				Rotation = nr(0, 360),
				RotSpeed = nr(-30, 30),
				Orientation = Enum.ParticleOrientation.FacingCamera,
			}},
		},
	},
	smoke_chimney = {
		kind = "loop", priority = 3, anchor = "Chimney", start = "on",
		use = "coal smoke mixed into the steam; darker, fewer, slower puffs; rate follows Speed",
		speed_link = {layers = {"soot"}, idle = 1.5, max = 5},
		layers = {
			{name = "soot", class = "ParticleEmitter", offset = Vector3.new(0, 0.5, 0), dir = Vector3.new(0, 1, 0), props = {
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 5,
				Lifetime = nr(3, 4.2),
				Speed = nr(5, 7),
				SpreadAngle = Vector2.new(10, 10),
				Acceleration = Vector3.new(0, 2, 0),
				Drag = 1,
				WindAffectsDrag = true,
				Size = ns({{0, 2}, {1, 10, 1.5}}),
				Transparency = ns({{0, 0.25}, {0.6, 0.5}, {1, 1}}),
				Color = cs({{0, hex("15181B")}, {0.5, hex("363A42")}, {1, hex("55503F")}}),
				LightEmission = 0,
				LightInfluence = 1,
				Rotation = nr(0, 360),
				RotSpeed = nr(-20, 20),
				Orientation = Enum.ParticleOrientation.FacingCamera,
			}},
		},
	},
	coal_dust = {
		kind = "burst", priority = 2, anchor = "Firebox", start = "on",
		use = "one shovel into the firebox: dust puff, embers and a firebox flare",
		layers = {
			{name = "dust", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 0.5, -1), emit = 14, props = {
				Texture = "rbxasset://textures/particles/smoke_main.dds",
				Rate = 0,
				Lifetime = nr(0.8, 1.4),
				Speed = nr(3, 6),
				SpreadAngle = Vector2.new(40, 40),
				Acceleration = Vector3.new(0, -2, 0),
				Drag = 2.5,
				WindAffectsDrag = false,
				Size = ns({{0, 0.6}, {1, 2.6, 0.5}}),
				Transparency = ns({{0, 0.35}, {1, 1}}),
				Color = cs({{0, hex("262626")}, {1, hex("55503F")}}),
				LightEmission = 0,
				LightInfluence = 1,
				Rotation = nr(0, 360),
				RotSpeed = nr(-40, 40),
			}},
			{name = "embers", class = "ParticleEmitter", offset = Vector3.new(0, 0, 0), dir = Vector3.new(0, 1, 0), emit = 6, delay = 0.1, props = {
				Texture = "rbxasset://textures/particles/sparkles_main.dds",
				Rate = 0,
				Lifetime = nr(0.4, 0.9),
				Speed = nr(4, 9),
				SpreadAngle = Vector2.new(30, 30),
				Acceleration = Vector3.new(0, 6, 0),
				Drag = 1,
				WindAffectsDrag = false,
				Size = ns({{0, 0.18}, {1, 0.05}}),
				Transparency = ns({{0, 0}, {1, 1}}),
				Color = cs({{0, hex("FF9A3C")}, {1, hex("FF5A14")}}),
				LightEmission = 1,
				LightInfluence = 0,
			}},
			{name = "flare", class = "PointLight", offset = Vector3.new(0, 0, 0), pulse = {peak = 4, duration = 0.35}, props = {
				Brightness = 0,
				Range = 9,
				Color = hex("FF7A22"),
				Shadows = false,
			}},
		},
	},
	headlamp = {
		kind = "loop", priority = 2, anchor = "Headlamp", start = "on",
		use = "loco headlamp for tunnels and night: spot light plus a soft beam cone (glow colour style.thumb.glow; tunnel and night use proposed)",
		layers = {
			{name = "spot", class = "SpotLight", offset = Vector3.new(0.2, 0, 0), dir = Vector3.new(1, -0.08, 0), props = {
				Brightness = 3,
				Range = 60,
				Angle = 50,
				Face = Enum.NormalId.Front,
				Color = hex("FFF6C8"),
				Shadows = false,
			}},
			{name = "cone", class = "Beam", offset = Vector3.new(0.3, 0, 0), a1 = Vector3.new(40, -3, 0), props = {
				Width0 = 1.5,
				Width1 = 22,
				Segments = 1,
				FaceCamera = true,
				Transparency = ns({{0, 0.72}, {1, 1}}),
				Color = cs({{0, hex("FFF6C8")}, {1, hex("FFF6C8")}}),
				LightEmission = 1,
				LightInfluence = 0,
			}},
		},
	},
	sparks_brake = {
		kind = "loop", priority = 2, anchor = "BrakeShoe", start = "off",
		use = "brakes on (station arrival, pressure-crisis brake): fans of sparks thrown out past both body sides and back from the loco wheels, plus a ground glow; rate and glow follow Speed so they die as the train stops. Effect proposed: canon has the brake, not brake sparks",
		speed_link = {layers = {"fan_r", "fan_l", "glow"}, idle = 0, max = 80},
		layers = {
			{name = "fan_r", class = "ParticleEmitter", offset = Vector3.new(0, 0, 4), dir = Vector3.new(-0.35, 0.5, 0.8), props = {
				Texture = "rbxasset://textures/particles/sparkles_main.dds",
				Rate = 80,
				Lifetime = nr(0.4, 0.8),
				Speed = nr(30, 44),
				SpreadAngle = Vector2.new(20, 12),
				Acceleration = Vector3.new(0, -50, 0),
				Drag = 0.4,
				WindAffectsDrag = true,
				Size = ns({{0, 2.2}, {1, 0.8}}),
				Transparency = ns({{0, 0}, {0.7, 0.2}, {1, 1}}),
				Color = cs({{0, hex("FFF6C8")}, {0.4, hex("FF9A3C")}, {1, hex("FF5A14")}}),
				LightEmission = 0.7,
				LightInfluence = 0,
				Brightness = 2.5,
				Squash = ns({{0, 1.5}, {1, 1.5}}),
				Orientation = Enum.ParticleOrientation.VelocityParallel,
			}},
			{name = "fan_l", class = "ParticleEmitter", offset = Vector3.new(0, 0, -4), dir = Vector3.new(-0.35, 0.5, -0.8), props = {
				Texture = "rbxasset://textures/particles/sparkles_main.dds",
				Rate = 80,
				Lifetime = nr(0.4, 0.8),
				Speed = nr(30, 44),
				SpreadAngle = Vector2.new(20, 12),
				Acceleration = Vector3.new(0, -50, 0),
				Drag = 0.4,
				WindAffectsDrag = true,
				Size = ns({{0, 2.2}, {1, 0.8}}),
				Transparency = ns({{0, 0}, {0.7, 0.2}, {1, 1}}),
				Color = cs({{0, hex("FFF6C8")}, {0.4, hex("FF9A3C")}, {1, hex("FF5A14")}}),
				LightEmission = 0.7,
				LightInfluence = 0,
				Brightness = 2.5,
				Squash = ns({{0, 1.5}, {1, 1.5}}),
				Orientation = Enum.ParticleOrientation.VelocityParallel,
			}},
			{name = "glow", class = "PointLight", offset = Vector3.new(0, 1, 0), flicker = {min = 0.75, max = 1, hz = 3}, props = {
				Brightness = 2,
				Range = 12,
				Color = hex("FF9A3C"),
				Shadows = false,
			}},
		},
	},
}

return P
