-- HudTickets (ModuleScript) - GENERATED by rr-ui-foundry from hud_tickets.json. Do not edit: change the spec
-- and run ui.py build. Rects are design px of the phone board; RR_UIKit turns them into Scale + pins.
return {
	name = "HudTickets",
	title = "HUD notification stack (ticket frame)",
	insets = "CoreUISafeInsets",
	displayOrder = 20,
	modal = false,
	data = {},
	nodes = {
		{
			id = "stack",
			["type"] = "stack",
			rect = { 540, 58, 290, 220 },
			pin = "br",
			avoid = { "jump" },
			stack = {
				template = "ticket",
				compact = "ticket_compact",
				dir = "up",
				gap = 8,
				max = 4,
				max_lifted = 3,
				full = { "newest", "newest_crisis" },
				crisis = "kind=danger",
				sticky = "kind=danger",
				merge = "type",
				life_s = {
					danger = 7,
					risk = 6,
					cash = 4.5,
					info = 5,
				},
				overflow = "more_chip",
				feel = {
					enter = "hud_ticket_enter",
					leave = "hud_ticket_leave",
					merge = "hud_merge_bump",
					crisis = "hud_crisis_arrival",
				},
			},
			layer = "core",
		},
	},
	types = {
		CoalLow = {
			kind = "danger",
			icon = "coal",
			title = "COAL LOW!",
			body = "Shovel coal in the firebox!",
			stamp = nil,
		},
		PressureHigh = {
			kind = "danger",
			icon = "gauge",
			title = "PRESSURE HIGH!",
			body = "The boiler's gonna blow!",
			stamp = nil,
		},
		Breakdown = {
			kind = "danger",
			icon = "wrench",
			title = "BREAKDOWN!",
			body = "Grab a wrench and fix it!",
			stamp = nil,
		},
		PassengersUpset = {
			kind = "danger",
			icon = "passenger",
			title = "PASSENGERS UPSET!",
			body = "Check the carriages, fast!",
			stamp = nil,
		},
		JunctionAhead = {
			kind = "risk",
			icon = "lever",
			title = "JUNCTION AHEAD!",
			body = "Safe or risky? Pull it!",
			stamp = nil,
		},
		RiskyRoute = {
			kind = "risk",
			icon = "fork",
			title = "RISKY ROUTE!",
			body = "Multiplier up",
			stamp = "X2",
		},
		FareBanked = {
			kind = "cash",
			icon = "coin",
			title = "FARE BANKED!",
			body = "Station paid out",
			stamp = "$120",
		},
		CrateLanded = {
			kind = "info",
			icon = "crate",
			title = "CRATE LANDED!",
			body = "Grab it before it slides off!",
			stamp = nil,
		},
		CrewJoined = {
			kind = "info",
			icon = "crew_join",
			title = "CREW JOINED!",
			body = "{name} is aboard",
			stamp = nil,
		},
		CrewLeft = {
			kind = "info",
			icon = "crew_leave",
			title = "CREW LEFT!",
			body = "{name} left the train",
			stamp = nil,
		},
	},
	nav = {
		edges = {},
		default = nil,
		back = nil,
		modal = nil,
	},
	machine = nil,
	boards = {
		{
			name = "routine",
			push = {
				{
					"CrewJoined",
					{
						name = "Joel",
					},
				},
				{ "CrateLanded" },
				{ "FareBanked" },
			},
			life = { 0.35, 0.6, 0.9 },
		},
		{
			name = "crisis",
			push = {
				{ "JunctionAhead" },
				{ "Breakdown" },
				{ "FareBanked" },
				{ "CoalLow" },
			},
			life = { 0.4, 1, 0.7, 1 },
		},
		{
			name = "overflow",
			push = {
				{
					"CrewJoined",
					{
						name = "Sam",
					},
				},
				{ "CrateLanded" },
				{ "PressureHigh" },
				{ "RiskyRoute" },
				{ "FareBanked" },
				{ "FareBanked" },
				{
					"CrewLeft",
					{
						name = "Ava",
					},
				},
			},
			life = { 0.2, 0.3, 1, 0.5, 0.8, 0.8, 0.95 },
		},
	},
}
