-- LobbyCreateMatch (ModuleScript) - GENERATED by rr-ui-foundry from lobby_create_match.json. Do not edit: change the spec
-- and run ui.py build. Rects are design px of the phone board; RR_UIKit turns them into Scale + pins.
return {
	name = "LobbyCreateMatch",
	title = "Create match (lobby modal)",
	insets = "CoreUISafeInsets",
	displayOrder = 30,
	modal = true,
	data = {
		players = {
			values = { 1, 2, 3 },
			default = 2,
		},
		difficulty = {
			values = { "EASY", "MEDIUM", "HARD", "INSANE" },
			default = "MEDIUM",
		},
	},
	nodes = {
		{
			id = "scrim",
			["type"] = "frame",
			layer = "backdrop",
			rect = { 0, 0, 844, 390 },
			stretch = "xy",
			fill = "scrim",
			alpha = 0.55,
		},
		{
			["type"] = "frame",
			comp = "panel",
			feel = "panel",
			id = "panel",
			pin = "cc",
			rect = { 192, 72, 460, 303 },
			template = "panel",
			children = {
				{
					id = "panel.shadow",
					["type"] = "frame",
					rect = { 0, 6, 460, 297 },
					fill = "shadow",
					alpha = 0.5,
					radius = 16,
				},
				{
					id = "panel.body",
					["type"] = "frame",
					rect = { 0, 0, 460, 297 },
					fill = "panel",
					stroke = { "ink", 3 },
					radius = 16,
					clip = true,
					content = true,
					children = {
						{
							id = "panel.header",
							["type"] = "frame",
							rect = { 0, 0, 460, 56 },
							fill = "header",
							children = {
								{
									id = "panel.title",
									["type"] = "text",
									rect = { 16, 0, 384, 56 },
									text = "CREATE MATCH",
									style = "title",
									color = "on_header",
								},
							},
						},
						{
							id = "panel.rule",
							["type"] = "frame",
							rect = { 0, 56, 460, 3 },
							fill = "trim",
						},
						{
							id = "ico_players",
							["type"] = "image",
							rect = { 20, 88, 32, 21 },
							image = "icon.crew",
							tint = "header",
						},
						{
							id = "lbl_players",
							["type"] = "text",
							rect = { 60, 73, 150, 52 },
							text = "PLAYERS",
							style = "label",
							color = "text",
						},
						{
							["type"] = "hit",
							comp = "chip",
							feel = "button",
							id = "p1",
							on = "players=1",
							action = {
								set = {
									players = 1,
								},
							},
							rect = { 264, 73, 52, 52 },
							template = "chip",
							states = {
								on = {
									["p1.face"] = {
										fill = "accent",
										stroke = { "ink", 3 },
									},
									["p1.label"] = {
										color = "on_accent",
									},
									["p1.mark"] = {
										visible = true,
									},
								},
								pressed = {
									["p1.face"] = {
										dy = 2,
									},
								},
								disabled = {
									p1 = {
										alpha = 0.45,
									},
								},
							},
							children = {
								{
									id = "p1.face",
									["type"] = "frame",
									rect = { 0, 0, 52, 52 },
									fill = "btn",
									stroke = { "ink", 2 },
									radius = 12,
									children = {
										{
											id = "p1.label",
											["type"] = "text",
											rect = { 0, 0, 52, 48 },
											text = "1",
											style = "chip",
											color = "on_btn",
											align = "center",
										},
										{
											id = "p1.mark",
											["type"] = "frame",
											rect = { 17, 43, 18, 4 },
											fill = "ink",
											radius = 2,
											visible = false,
										},
									},
								},
							},
						},
						{
							["type"] = "hit",
							comp = "chip",
							feel = "button",
							id = "p2",
							on = "players=2",
							action = {
								set = {
									players = 2,
								},
							},
							rect = { 326, 73, 52, 52 },
							template = "chip",
							states = {
								on = {
									["p2.face"] = {
										fill = "accent",
										stroke = { "ink", 3 },
									},
									["p2.label"] = {
										color = "on_accent",
									},
									["p2.mark"] = {
										visible = true,
									},
								},
								pressed = {
									["p2.face"] = {
										dy = 2,
									},
								},
								disabled = {
									p2 = {
										alpha = 0.45,
									},
								},
							},
							children = {
								{
									id = "p2.face",
									["type"] = "frame",
									rect = { 0, 0, 52, 52 },
									fill = "btn",
									stroke = { "ink", 2 },
									radius = 12,
									children = {
										{
											id = "p2.label",
											["type"] = "text",
											rect = { 0, 0, 52, 48 },
											text = "2",
											style = "chip",
											color = "on_btn",
											align = "center",
										},
										{
											id = "p2.mark",
											["type"] = "frame",
											rect = { 17, 43, 18, 4 },
											fill = "ink",
											radius = 2,
											visible = false,
										},
									},
								},
							},
						},
						{
							["type"] = "hit",
							comp = "chip",
							feel = "button",
							id = "p3",
							on = "players=3",
							action = {
								set = {
									players = 3,
								},
							},
							rect = { 388, 73, 52, 52 },
							template = "chip",
							states = {
								on = {
									["p3.face"] = {
										fill = "accent",
										stroke = { "ink", 3 },
									},
									["p3.label"] = {
										color = "on_accent",
									},
									["p3.mark"] = {
										visible = true,
									},
								},
								pressed = {
									["p3.face"] = {
										dy = 2,
									},
								},
								disabled = {
									p3 = {
										alpha = 0.45,
									},
								},
							},
							children = {
								{
									id = "p3.face",
									["type"] = "frame",
									rect = { 0, 0, 52, 52 },
									fill = "btn",
									stroke = { "ink", 2 },
									radius = 12,
									children = {
										{
											id = "p3.label",
											["type"] = "text",
											rect = { 0, 0, 52, 48 },
											text = "3",
											style = "chip",
											color = "on_btn",
											align = "center",
										},
										{
											id = "p3.mark",
											["type"] = "frame",
											rect = { 17, 43, 18, 4 },
											fill = "ink",
											radius = 2,
											visible = false,
										},
									},
								},
							},
						},
						{
							id = "row_rule",
							["type"] = "frame",
							rect = { 20, 137, 420, 2 },
							fill = "trim",
							alpha = 0.5,
						},
						{
							id = "ico_diff",
							["type"] = "image",
							rect = { 20, 164, 32, 21 },
							image = "icon.tiers",
							tint = "header",
						},
						{
							id = "lbl_diff",
							["type"] = "text",
							rect = { 60, 149, 118, 52 },
							text = "DIFFICULTY",
							style = "label",
							color = "text",
						},
						{
							["type"] = "hit",
							comp = "button",
							feel = "button",
							id = "diff_prev",
							action = {
								cycle = {
									difficulty = -1,
								},
							},
							rect = { 184, 149, 52, 56 },
							template = "button",
							variant = "icon",
							states = {
								hover = {
									["diff_prev.face"] = {
										dy = -1,
									},
								},
								pressed = {
									["diff_prev.face"] = {
										dy = 3,
										fill = "btn_dark",
									},
								},
								disabled = {
									diff_prev = {
										alpha = 0.45,
									},
								},
							},
							children = {
								{
									id = "diff_prev.shadow",
									["type"] = "frame",
									rect = { 0, 4, 52, 52 },
									fill = "shadow",
									alpha = 0.9,
									radius = 12,
								},
								{
									id = "diff_prev.face",
									["type"] = "frame",
									rect = { 0, 0, 52, 52 },
									fill = "btn",
									stroke = { "ink", 3 },
									radius = 12,
									children = {
										{
											id = "diff_prev.label",
											["type"] = "text",
											rect = { 6, 0, 40, 52 },
											text = "<",
											style = "chip",
											color = "on_btn",
											align = "center",
											truncate = true,
										},
									},
								},
							},
						},
						{
							id = "diff_plate",
							["type"] = "frame",
							rect = { 246, 149, 132, 52 },
							fill = "accent",
							stroke = { "ink", 3 },
							radius = 12,
							children = {
								{
									id = "diff_pip",
									["type"] = "frame",
									rect = { 12, 16, 20, 20 },
									fill = "diff.{difficulty|lower}",
									stroke = { "ink", 2 },
									radius = "circle",
								},
								{
									id = "diff_value",
									["type"] = "text",
									rect = { 36, 0, 90, 52 },
									text = "{difficulty}",
									style = "value",
									color = "on_accent",
									align = "center",
								},
							},
						},
						{
							["type"] = "hit",
							comp = "button",
							feel = "button",
							id = "diff_next",
							action = {
								cycle = {
									difficulty = 1,
								},
							},
							rect = { 388, 149, 52, 56 },
							template = "button",
							variant = "icon",
							states = {
								hover = {
									["diff_next.face"] = {
										dy = -1,
									},
								},
								pressed = {
									["diff_next.face"] = {
										dy = 3,
										fill = "btn_dark",
									},
								},
								disabled = {
									diff_next = {
										alpha = 0.45,
									},
								},
							},
							children = {
								{
									id = "diff_next.shadow",
									["type"] = "frame",
									rect = { 0, 4, 52, 52 },
									fill = "shadow",
									alpha = 0.9,
									radius = 12,
								},
								{
									id = "diff_next.face",
									["type"] = "frame",
									rect = { 0, 0, 52, 52 },
									fill = "btn",
									stroke = { "ink", 3 },
									radius = 12,
									children = {
										{
											id = "diff_next.label",
											["type"] = "text",
											rect = { 6, 0, 40, 52 },
											text = ">",
											style = "chip",
											color = "on_btn",
											align = "center",
											truncate = true,
										},
									},
								},
							},
						},
						{
							["type"] = "hit",
							comp = "button",
							feel = "button",
							id = "join",
							action = "join",
							rect = { 20, 217, 420, 60 },
							template = "button",
							variant = "primary",
							hint = "ButtonA",
							states = {
								hover = {
									["join.face"] = {
										dy = -1,
									},
								},
								pressed = {
									["join.face"] = {
										dy = 3,
										fill = "accent_dark",
									},
								},
								disabled = {
									join = {
										alpha = 0.45,
									},
								},
							},
							children = {
								{
									id = "join.shadow",
									["type"] = "frame",
									rect = { 0, 4, 420, 56 },
									fill = "shadow",
									alpha = 0.9,
									radius = 12,
								},
								{
									id = "join.face",
									["type"] = "frame",
									rect = { 0, 0, 420, 56 },
									fill = "accent",
									stroke = { "ink", 3 },
									radius = 12,
									children = {
										{
											id = "join.label",
											["type"] = "text",
											rect = { 6, 0, 408, 56 },
											text = "JOIN",
											style = "button",
											color = "on_accent",
											align = "center",
											truncate = true,
										},
										{
											id = "join.glyphs",
											["type"] = "frame",
											rect = { 0, 0, 420, 56 },
											children = {
												{
													id = "join.glyph",
													["type"] = "image",
													rect = { 8, 16, 24, 24 },
													image = "key.ButtonA",
													gamepad_only = true,
												},
											},
										},
									},
								},
							},
						},
					},
				},
				{
					["type"] = "hit",
					comp = "button",
					feel = "button",
					id = "panel.close",
					action = "close",
					rect = { 404, 2, 52, 52 },
					template = "button",
					variant = "icon",
					hint = "ButtonB",
					states = {
						hover = {
							["panel.close.face"] = {
								dy = -1,
							},
						},
						pressed = {
							["panel.close.face"] = {
								dy = 3,
								fill = "btn_dark",
							},
						},
						disabled = {
							["panel.close"] = {
								alpha = 0.45,
							},
						},
					},
					children = {
						{
							id = "panel.close.shadow",
							["type"] = "frame",
							rect = { 0, 4, 52, 48 },
							fill = "shadow",
							alpha = 0.9,
							radius = 12,
						},
						{
							id = "panel.close.face",
							["type"] = "frame",
							rect = { 0, 0, 52, 48 },
							fill = "btn",
							stroke = { "ink", 3 },
							radius = 12,
							children = {
								{
									id = "panel.close.label",
									["type"] = "text",
									rect = { 6, 0, 40, 48 },
									text = "X",
									style = "chip",
									color = "on_btn",
									align = "center",
									truncate = true,
								},
								{
									id = "panel.close.glyphs",
									["type"] = "frame",
									rect = { 0, 0, 52, 48 },
									children = {
										{
											id = "panel.close.glyph_c",
											["type"] = "image",
											rect = { 12, 10, 28, 28 },
											fill = "btn",
											radius = "circle",
											image = "key.ButtonB",
											gamepad_only = true,
										},
									},
								},
							},
						},
					},
				},
			},
			layer = "core",
		},
	},
	types = {},
	nav = {
		edges = {
			p1 = {
				right = "p2",
				up = "panel.close",
				down = "diff_prev",
			},
			p2 = {
				left = "p1",
				right = "p3",
				up = "panel.close",
				down = "diff_next",
			},
			p3 = {
				left = "p2",
				up = "panel.close",
				down = "diff_next",
			},
			diff_prev = {
				right = "diff_next",
				up = "p1",
				down = "join",
			},
			diff_next = {
				left = "diff_prev",
				up = "p3",
				down = "join",
			},
			join = {
				up = "diff_prev",
			},
			["panel.close"] = {
				down = "p3",
			},
		},
		default = "join",
		back = "panel.close",
		modal = "panel",
	},
	machine = {
		initial = "closed",
		states = {
			closed = {
				hide = { "scrim", "panel" },
			},
			open = {},
			joining = {
				disable = { "join", "p1", "p2", "p3", "diff_prev", "diff_next" },
				text = {
					["join.label"] = "JOINING...",
				},
			},
		},
		transitions = {
			{
				from = "closed",
				event = "open",
				to = "open",
				feel = "ui_panel_open",
			},
			{
				from = "open",
				event = "close",
				to = "closed",
				feel = "ui_panel_close",
			},
			{
				from = "open",
				event = "join",
				to = "joining",
				feel = "ui_button_press",
			},
			{
				from = "joining",
				event = "cancel",
				to = "open",
				feel = nil,
			},
			{
				from = "joining",
				event = "joined",
				to = "closed",
				feel = "ui_panel_close",
			},
			{
				from = "joining",
				event = "close",
				to = "closed",
				feel = "ui_panel_close",
			},
		},
	},
	boards = {
		{
			name = "open",
			state = "open",
			data = {
				players = 2,
				difficulty = "MEDIUM",
			},
		},
		{
			name = "insane",
			state = "open",
			data = {
				players = 3,
				difficulty = "INSANE",
			},
			select = "join",
			comp_states = {
				diff_next = "pressed",
			},
		},
		{
			name = "joining",
			state = "joining",
			data = {
				players = 1,
				difficulty = "EASY",
			},
		},
	},
}
