-- RR_LightingPresets: GENERATED by rr-vfx-lighting (vfx.py build, 2026-09-28) from presets/lighting.json.
-- Do not edit: change the JSON and rebuild. Palette colours use hex(); light levels use lvl() (intensities, not palette).
local function hex(h) return Color3.fromHex(h) end
local function lvl(r, g, b) return Color3.fromRGB(r, g, b) end

local P = {}

P.default = "grassland.day"
P.looks = {
	["grassland.day"] = {
		Lighting = {ClockTime = 14.2, GeographicLatitude = 41.7, Brightness = 2.4, ExposureCompensation = 0, OutdoorAmbient = lvl(70, 80, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(24, 22, 14), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.3, Offset = 0.12, Color = hex("C2CAB0"), Decay = hex("9FB0A8"), Glare = 0.2, Haze = 1.4},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.12, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 252, 244)},
		BloomEffect = {Enabled = true, Intensity = 0.35, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0.035, Spread = 0.55},
		fx_on = {},
	},
	["grassland.golden"] = {
		Lighting = {ClockTime = 17.3, GeographicLatitude = 41.7, Brightness = 1.9, ExposureCompensation = 0.1, OutdoorAmbient = lvl(78, 76, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(70, 42, 12), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.32, Offset = 0.12, Color = hex("EFE4C8"), Decay = hex("93A6A2"), Glare = 0.8, Haze = 1.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.1, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 246, 232)},
		BloomEffect = {Enabled = true, Intensity = 0.55, Size = 22, Threshold = 1.2},
		SunRaysEffect = {Enabled = true, Intensity = 0.1, Spread = 0.7},
		fx_on = {},
	},
	["grassland.dusk"] = {
		Lighting = {ClockTime = 17.85, GeographicLatitude = 41.7, Brightness = 1.3, ExposureCompensation = 0.45, OutdoorAmbient = lvl(62, 64, 80), Ambient = lvl(36, 38, 48), EnvironmentDiffuseScale = 0.28, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(66, 34, 22), ColorShift_Bottom = lvl(6, 6, 14), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.33, Offset = 0.12, Color = hex("C4B6B4"), Decay = hex("566079"), Glare = 0.6, Haze = 1.7},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.06, Contrast = 0.08, Brightness = 0, TintColor = lvl(255, 242, 240)},
		BloomEffect = {Enabled = true, Intensity = 0.6, Size = 22, Threshold = 1.1},
		SunRaysEffect = {Enabled = true, Intensity = 0.08, Spread = 0.8},
		fx_on = {"headlamp"},
	},
	["grassland.night"] = {
		Lighting = {ClockTime = 0.5, GeographicLatitude = 41.7, Brightness = 1.4, ExposureCompensation = 0.9, OutdoorAmbient = lvl(56, 62, 78), Ambient = lvl(30, 34, 42), EnvironmentDiffuseScale = 0.2, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(10, 14, 24), ColorShift_Bottom = lvl(0, 0, 0), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.34, Offset = 0.12, Color = hex("1B2540"), Decay = hex("07090F"), Glare = 0, Haze = 0.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0, Contrast = 0.1, Brightness = 0, TintColor = lvl(236, 242, 255)},
		BloomEffect = {Enabled = true, Intensity = 0.8, Size = 28, Threshold = 0.95},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"headlamp"},
	},
	["grassland.storm"] = {
		Lighting = {ClockTime = 13.5, GeographicLatitude = 41.7, Brightness = 1.1, ExposureCompensation = 0, OutdoorAmbient = lvl(74, 80, 82), Ambient = lvl(40, 44, 46), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(0, 0, 0), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.6},
		Atmosphere = {Density = 0.42, Offset = 0.12, Color = hex("8A8D98"), Decay = hex("363A42"), Glare = 0, Haze = 2.6},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0, Contrast = 0.08, Brightness = 0, TintColor = lvl(240, 246, 248)},
		BloomEffect = {Enabled = true, Intensity = 0.2, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"rain"},
	},
	["cutting.day"] = {
		Lighting = {ClockTime = 14.2, GeographicLatitude = 41.7, Brightness = 2.4, ExposureCompensation = 0, OutdoorAmbient = lvl(63, 72, 63), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.28, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(24, 22, 14), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.26, Offset = 0.12, Color = hex("C2CAB0"), Decay = hex("9FB0A8"), Glare = 0.2, Haze = 1.4},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.12, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 252, 244)},
		BloomEffect = {Enabled = true, Intensity = 0.35, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0.035, Spread = 0.55},
		fx_on = {},
	},
	["cutting.golden"] = {
		Lighting = {ClockTime = 17.3, GeographicLatitude = 41.7, Brightness = 1.9, ExposureCompensation = 0.1, OutdoorAmbient = lvl(70, 68, 63), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.28, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(70, 42, 12), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.28, Offset = 0.12, Color = hex("EFE4C8"), Decay = hex("93A6A2"), Glare = 0.8, Haze = 1.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.1, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 246, 232)},
		BloomEffect = {Enabled = true, Intensity = 0.55, Size = 22, Threshold = 1.2},
		SunRaysEffect = {Enabled = true, Intensity = 0.1, Spread = 0.7},
		fx_on = {},
	},
	["cutting.night"] = {
		Lighting = {ClockTime = 0.5, GeographicLatitude = 41.7, Brightness = 1.4, ExposureCompensation = 0.9, OutdoorAmbient = lvl(50, 56, 70), Ambient = lvl(30, 34, 42), EnvironmentDiffuseScale = 0.16, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(10, 14, 24), ColorShift_Bottom = lvl(0, 0, 0), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.3, Offset = 0.12, Color = hex("1B2540"), Decay = hex("07090F"), Glare = 0, Haze = 0.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0, Contrast = 0.1, Brightness = 0, TintColor = lvl(236, 242, 255)},
		BloomEffect = {Enabled = true, Intensity = 0.8, Size = 28, Threshold = 0.95},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"headlamp"},
	},
	["cutting.storm"] = {
		Lighting = {ClockTime = 13.5, GeographicLatitude = 41.7, Brightness = 1.1, ExposureCompensation = 0, OutdoorAmbient = lvl(67, 72, 74), Ambient = lvl(40, 44, 46), EnvironmentDiffuseScale = 0.28, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(0, 0, 0), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.6},
		Atmosphere = {Density = 0.38, Offset = 0.12, Color = hex("8A8D98"), Decay = hex("363A42"), Glare = 0, Haze = 2.6},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0, Contrast = 0.08, Brightness = 0, TintColor = lvl(240, 246, 248)},
		BloomEffect = {Enabled = true, Intensity = 0.2, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"rain"},
	},
	["viaduct.day"] = {
		Lighting = {ClockTime = 14.2, GeographicLatitude = 41.7, Brightness = 2.4, ExposureCompensation = 0, OutdoorAmbient = lvl(70, 80, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(24, 22, 14), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.4, Offset = 0.12, Color = hex("C2CAB0"), Decay = hex("9FB0A8"), Glare = 0.2, Haze = 2.6},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.12, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 252, 244)},
		BloomEffect = {Enabled = true, Intensity = 0.35, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0.035, Spread = 0.55},
		fx_on = {},
	},
	["viaduct.golden"] = {
		Lighting = {ClockTime = 17.3, GeographicLatitude = 41.7, Brightness = 1.9, ExposureCompensation = 0.1, OutdoorAmbient = lvl(78, 76, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(70, 42, 12), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.42, Offset = 0.12, Color = hex("EFE4C8"), Decay = hex("93A6A2"), Glare = 0.8, Haze = 3},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.1, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 246, 232)},
		BloomEffect = {Enabled = true, Intensity = 0.55, Size = 22, Threshold = 1.2},
		SunRaysEffect = {Enabled = true, Intensity = 0.1, Spread = 0.7},
		fx_on = {},
	},
	["viaduct.night"] = {
		Lighting = {ClockTime = 0.5, GeographicLatitude = 41.7, Brightness = 1.4, ExposureCompensation = 0.9, OutdoorAmbient = lvl(56, 62, 78), Ambient = lvl(30, 34, 42), EnvironmentDiffuseScale = 0.2, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(10, 14, 24), ColorShift_Bottom = lvl(0, 0, 0), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.44, Offset = 0.12, Color = hex("1B2540"), Decay = hex("07090F"), Glare = 0, Haze = 2},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0, Contrast = 0.1, Brightness = 0, TintColor = lvl(236, 242, 255)},
		BloomEffect = {Enabled = true, Intensity = 0.8, Size = 28, Threshold = 0.95},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"headlamp"},
	},
	["viaduct.storm"] = {
		Lighting = {ClockTime = 13.5, GeographicLatitude = 41.7, Brightness = 1.1, ExposureCompensation = 0, OutdoorAmbient = lvl(74, 80, 82), Ambient = lvl(40, 44, 46), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(0, 0, 0), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.6},
		Atmosphere = {Density = 0.52, Offset = 0.12, Color = hex("8A8D98"), Decay = hex("363A42"), Glare = 0, Haze = 3.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0, Contrast = 0.08, Brightness = 0, TintColor = lvl(240, 246, 248)},
		BloomEffect = {Enabled = true, Intensity = 0.2, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"rain"},
	},
	["yard.day"] = {
		Lighting = {ClockTime = 14.2, GeographicLatitude = 41.7, Brightness = 2.4, ExposureCompensation = 0, OutdoorAmbient = lvl(70, 80, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(24, 22, 14), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.35, Offset = 0.12, Color = hex("C2CAB0"):Lerp(hex("8A8D98"), 0.35), Decay = hex("9FB0A8"), Glare = 0.2, Haze = 1.4},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.07, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 252, 244)},
		BloomEffect = {Enabled = true, Intensity = 0.35, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0.035, Spread = 0.55},
		fx_on = {},
	},
	["yard.golden"] = {
		Lighting = {ClockTime = 17.3, GeographicLatitude = 41.7, Brightness = 1.9, ExposureCompensation = 0.1, OutdoorAmbient = lvl(78, 76, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(70, 42, 12), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.37, Offset = 0.12, Color = hex("EFE4C8"):Lerp(hex("8A8D98"), 0.35), Decay = hex("93A6A2"), Glare = 0.8, Haze = 1.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.05, Contrast = 0.05, Brightness = 0, TintColor = lvl(255, 246, 232)},
		BloomEffect = {Enabled = true, Intensity = 0.55, Size = 22, Threshold = 1.2},
		SunRaysEffect = {Enabled = true, Intensity = 0.1, Spread = 0.7},
		fx_on = {},
	},
	["yard.night"] = {
		Lighting = {ClockTime = 0.5, GeographicLatitude = 41.7, Brightness = 1.4, ExposureCompensation = 0.9, OutdoorAmbient = lvl(56, 62, 78), Ambient = lvl(30, 34, 42), EnvironmentDiffuseScale = 0.2, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(10, 14, 24), ColorShift_Bottom = lvl(0, 0, 0), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.39, Offset = 0.12, Color = hex("1B2540"):Lerp(hex("8A8D98"), 0.35), Decay = hex("07090F"), Glare = 0, Haze = 0.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = -0.05, Contrast = 0.1, Brightness = 0, TintColor = lvl(236, 242, 255)},
		BloomEffect = {Enabled = true, Intensity = 0.8, Size = 28, Threshold = 0.95},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"headlamp"},
	},
	["yard.storm"] = {
		Lighting = {ClockTime = 13.5, GeographicLatitude = 41.7, Brightness = 1.1, ExposureCompensation = 0, OutdoorAmbient = lvl(74, 80, 82), Ambient = lvl(40, 44, 46), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(0, 0, 0), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.6},
		Atmosphere = {Density = 0.47, Offset = 0.12, Color = hex("8A8D98"):Lerp(hex("8A8D98"), 0.35), Decay = hex("363A42"), Glare = 0, Haze = 2.6},
		ColorCorrectionEffect = {Enabled = true, Saturation = -0.05, Contrast = 0.08, Brightness = 0, TintColor = lvl(240, 246, 248)},
		BloomEffect = {Enabled = true, Intensity = 0.2, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0, Spread = 0.55},
		fx_on = {"rain"},
	},
	["depot.day"] = {
		Lighting = {ClockTime = 14.2, GeographicLatitude = 41.7, Brightness = 2.4, ExposureCompensation = 0, OutdoorAmbient = lvl(70, 80, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(24, 22, 14), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.22, Offset = 0.12, Color = hex("C2CAB0"), Decay = hex("9FB0A8"), Glare = 0.2, Haze = 1.4},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.12, Contrast = 0.08, Brightness = 0, TintColor = lvl(255, 252, 244)},
		BloomEffect = {Enabled = true, Intensity = 0.35, Size = 22, Threshold = 1.4},
		SunRaysEffect = {Enabled = true, Intensity = 0.035, Spread = 0.55},
		fx_on = {},
	},
	["depot.golden"] = {
		Lighting = {ClockTime = 17.3, GeographicLatitude = 41.7, Brightness = 1.9, ExposureCompensation = 0.1, OutdoorAmbient = lvl(78, 76, 70), Ambient = lvl(44, 50, 48), EnvironmentDiffuseScale = 0.35, EnvironmentSpecularScale = 0.25, ColorShift_Top = lvl(70, 42, 12), ColorShift_Bottom = lvl(0, 6, 4), ShadowSoftness = 0.2},
		Atmosphere = {Density = 0.24, Offset = 0.12, Color = hex("EFE4C8"), Decay = hex("93A6A2"), Glare = 0.8, Haze = 1.8},
		ColorCorrectionEffect = {Enabled = true, Saturation = 0.1, Contrast = 0.08, Brightness = 0, TintColor = lvl(255, 246, 232)},
		BloomEffect = {Enabled = true, Intensity = 0.55, Size = 22, Threshold = 1.2},
		SunRaysEffect = {Enabled = true, Intensity = 0.1, Spread = 0.7},
		fx_on = {},
	},
}

P.overrides = {
	tunnel_under = {
		tween_in = 0.35, tween_out = 0.8, duration = nil,
		fx_on = {"headlamp"},
		ops = {
			Lighting = {Brightness = {"mul", 0.2}, OutdoorAmbient = {"mul", 1}, Ambient = {"mul", 1.3}, EnvironmentDiffuseScale = {"mul", 0.2}, ExposureCompensation = {"add", 0.8}},
			Atmosphere = {Density = {"mul", 0.4}, Color = {"lerp", hex("15181B"), 0.8}, Decay = {"lerp", hex("15181B"), 0.8}},
			BloomEffect = {Threshold = {"mul", 0.7}},
			SunRaysEffect = {Intensity = {"set", 0}},
		},
	},
	overbridge_flash = {
		tween_in = 0.08, tween_out = 0.35, duration = 0.6,
		fx_on = {},
		ops = {
			Lighting = {Brightness = {"mul", 0.5}, OutdoorAmbient = {"mul", 0.6}, Ambient = {"mul", 0.6}},
		},
	},
}

P.phone_post_off = {"BloomEffect", "SunRaysEffect", "DepthOfFieldEffect"} -- assumed (OQ-029 default A): not canon until the owner decides; re-measure at the alpha live check (tech.streaming.live_check)

return P
