-- studio_lighting_setup.lua: GENERATED by rr-vfx-lighting (vfx.py build, 2026-09-28).
-- Paste into Studio's command bar once per place. It sets the Studio-level lighting options, lists effects
-- that would stack with the RRFX_ ones, and applies the default look for editing. It prints every old value.
local function hex(h) return Color3.fromHex(h) end
local function lvl(r, g, b) return Color3.fromRGB(r, g, b) end
local L = game:GetService("Lighting")
local function set(inst, prop, v)
	local ok, old = pcall(function() return inst[prop] end)
	local done = pcall(function() inst[prop] = v end)
	print(string.format("%s.%s: %s -> %s%s", inst.Name, prop, tostring(ok and old), tostring(v), done and "" or " (FAILED: not settable here)"))
end
set(L, "LightingStyle", Enum.LightingStyle.Realistic) -- tech.lighting.technology_api
set(L, "PrioritizeLightingQuality", true)
set(game:GetService("MaterialService"), "Use2022Materials", false) -- tech.lighting.materials_2022 (canon)
print("Lighting.Technology is deprecated and not scriptable (RBXD 2026-09-28): LightingStyle replaces it.")
for _, c in ipairs(L:GetChildren()) do
	if (c:IsA("PostEffect") or c:IsA("Atmosphere") or c:IsA("Sky")) and string.sub(c.Name, 1, 5) ~= "RRFX_" then
		print("existing effect (stacks with RR_Lighting; disable it if the look doubles up):", c:GetFullName(), c.ClassName)
	end
end
local function ensure(cls)
	if cls == "Lighting" then return L end
	local inst = L:FindFirstChild("RRFX_" .. cls)
	if not inst and cls == "Atmosphere" then inst = L:FindFirstChildOfClass("Atmosphere") end
	if not inst then inst = Instance.new(cls); inst.Name = "RRFX_" .. cls; inst.Parent = L end
	return inst
end
-- default look: grassland.day
do local i = ensure("Lighting")
	set(i, "ClockTime", 14.2)
	set(i, "GeographicLatitude", 41.7)
	set(i, "Brightness", 2.4)
	set(i, "ExposureCompensation", 0)
	set(i, "OutdoorAmbient", lvl(70, 80, 70))
	set(i, "Ambient", lvl(44, 50, 48))
	set(i, "EnvironmentDiffuseScale", 0.35)
	set(i, "EnvironmentSpecularScale", 0.25)
	set(i, "ColorShift_Top", lvl(24, 22, 14))
	set(i, "ColorShift_Bottom", lvl(0, 6, 4))
	set(i, "ShadowSoftness", 0.2)
end
do local i = ensure("Atmosphere")
	set(i, "Density", 0.3)
	set(i, "Offset", 0.12)
	set(i, "Color", hex("C2CAB0"))
	set(i, "Decay", hex("9FB0A8"))
	set(i, "Glare", 0.2)
	set(i, "Haze", 1.4)
end
do local i = ensure("ColorCorrectionEffect")
	set(i, "Enabled", true)
	set(i, "Saturation", 0.12)
	set(i, "Contrast", 0.05)
	set(i, "Brightness", 0)
	set(i, "TintColor", lvl(255, 252, 244))
end
do local i = ensure("BloomEffect")
	set(i, "Enabled", true)
	set(i, "Intensity", 0.35)
	set(i, "Size", 22)
	set(i, "Threshold", 1.4)
end
do local i = ensure("SunRaysEffect")
	set(i, "Enabled", true)
	set(i, "Intensity", 0.035)
	set(i, "Spread", 0.55)
end
print("rr-vfx-lighting: studio setup done. Studio test pending (owner): check the look in Play Solo and on a phone emulator.")
