--[[
RR_Sound (rr-soundsmith): Risky Rails client sound runtime. ModuleScript in ReplicatedStorage, required by ONE
LocalScript. Reads RR_SoundMap (generated by `sound.py build`; never edit it by hand).

What it does
  * builds the SoundGroup tree (reuses SoundService.RR_Mix from studio_sound_setup.lua when present)
  * pre-makes a small pool of Sound instances per sound on the client (canon: never clone Sounds on the server)
  * voice caps: global and per group; when full, stops the least important voice (highest tier, oldest first);
    tiers up to voices.protectTier (crisis, fail) are never dropped; per-sound voice counts restart their own oldest
  * cooldowns, pitch spread, no-repeat variations, 3D emitters by role, a positional layer for 2D alarms
  * ducking in dB per group with attack / hold / release, stepped on Heartbeat
  * the wheel loop follows Speed (av.audio.speed_link); rr-game-feel cues (Feel.Cue) play their mapped events

API
  Sound.init(map, opts)            opts.feel = the RR_Feel module (optional); opts.folder = parent for 2D sounds
  Sound.event(name, ctx)           run an event's actions; ctx.pitch, ctx.gainDb, ctx.at, ctx.n (repeat index)
  Sound.play(id, opts)             one sound; opts.pitch (multiplier), opts.gainDb, opts.at (BasePart/Attachment)
  Sound.start(id) / stop(id) / toggle(id)     looped sounds
  Sound.setSpeed(speed)            on every throttle change
  Sound.setEmitter(role, inst)     Attachment or BasePart where 3D sounds of that role play
  Sound.setSetting(name, v)        master, sfx, ambient, music (0..1)
  Sound.duck(ruleName, seconds)    hold a ducking rule on for a scripted moment
  Sound.stats() · Sound.stopAll() · Sound.destroy() · Sound.step(dt) (exposed for tests)
Events marked via = "feel" play when RR_Feel plays that event; calling them with Sound.event while Feel is
connected is ignored (warned once) so nothing plays twice.
Written in the Lua 5.1 subset of Luau so it runs in the rr-soundsmith test VM.
]]

local Sound = {}

local SoundService = game:GetService("SoundService")
local RunService = game:GetService("RunService")

local Map = nil
local folder = nil
local feelConnected = false
local groups, parentOf, settingOf, gstate = {}, {}, {}, {}
local pools, active, loops, emitters = {}, {}, {}, {}
local lastPlay, repeatState, ruleUntil, speedState, warned = {}, {}, {}, {}, {}
local settings = {}
local conns = {}
local counters = { played = 0, dropped = 0, stolen = 0, cooled = 0, missing = 0, ignored = 0 }

Sound._now = os.clock

local function now()
	return Sound._now()
end

local function clamp(x, a, b)
	if x < a then
		return a
	elseif x > b then
		return b
	end
	return x
end

local function dbToGain(db)
	return 10 ^ (db / 20)
end

local function warnOnce(key, msg)
	if not warned[key] then
		warned[key] = true
		warn("[RR_Sound] " .. msg)
	end
end

local function inChain(g, set)
	while g do
		if set[g] then
			return true
		end
		g = parentOf[g]
	end
	return false
end

local function applyGroup(g)
	local sg, st = groups[g], gstate[g]
	if not sg or not st then
		return
	end
	local key = settingOf[g]
	local base = key and (settings[key] or 1) or 1
	sg.Volume = clamp(base * dbToGain(st.db), 0, 10)
end

local function makeSound(id, s, var, layer)
	local inst = Instance.new("Sound")
	inst.Name = id .. (layer and "_layer" or "") .. "_" .. var
	inst.SoundId = s.ids[((var - 1) % #s.ids) + 1]
	inst.Looped = s.looped
	inst.Volume = s.volume
	inst.SoundGroup = groups[s.group]
	local ro = layer and s.layer3d.rolloff or s.rolloff
	if ro then
		inst.RollOffMode = Enum.RollOffMode[ro.mode]
		inst.RollOffMinDistance = ro.min
		inst.RollOffMaxDistance = ro.max
	end
	inst.Parent = folder
	return inst
end

local function purge(t)
	local keep = {}
	for _, v in ipairs(active) do
		if v.entry.endsAt > t then
			table.insert(keep, v)
		end
	end
	active = keep
end

local function removeActive(entry)
	for i = #active, 1, -1 do
		if active[i].entry == entry then
			table.remove(active, i)
		end
	end
end

local function stopEntry(entry)
	entry.inst:Stop()
	entry.endsAt = 0
	removeActive(entry)
end

local function pickEntry(s, pool, t)
	local busy, free = 0, {}
	for _, e in ipairs(pool.entries) do
		if e.endsAt > t then
			busy = busy + 1
		else
			table.insert(free, e)
		end
	end
	if busy >= s.voices or #free == 0 then
		return nil
	end
	local fresh = {}
	for _, e in ipairs(free) do
		if e.var ~= pool.lastVar then
			table.insert(fresh, e)
		end
	end
	local from = #fresh > 0 and fresh or free
	return from[math.random(1, #from)]
end

local function oldestOwn(pool, t)
	local best = nil
	for _, e in ipairs(pool.entries) do
		if e.endsAt > t and (best == nil or e.startedAt < best.startedAt) then
			best = e
		end
	end
	return best or pool.entries[1]
end

local function findVictim(s, groupOnly)
	local best = nil
	for _, v in ipairs(active) do
		if (not groupOnly or v.group == s.group) and v.tier > s.tier then
			if best == nil or v.tier > best.tier or (v.tier == best.tier and v.startedAt < best.startedAt) then
				best = v
			end
		end
	end
	if best == nil and s.tier <= Map.voices.protectTier then
		for _, v in ipairs(active) do
			if (not groupOnly or v.group == s.group) and v.tier >= s.tier then
				if best == nil or v.tier > best.tier or (v.tier == best.tier and v.startedAt < best.startedAt) then
					best = v
				end
			end
		end
	end
	return best
end

local function applyLoop(id)
	local s, pool = Map.sounds[id], pools[id]
	if not pool or #pool.entries == 0 then
		return
	end
	local st = speedState[id]
	local inst = pool.entries[1].inst
	inst.PlaybackSpeed = st and st.rate or 1
	inst.Volume = clamp(s.volume * (st and st.gain or 1), 0, 10)
end

function Sound.play(id, opts)
	opts = opts or {}
	local s = Map and Map.sounds[id]
	if not s then
		warnOnce("nosound:" .. tostring(id), "unknown sound " .. tostring(id))
		return nil
	end
	local pool = pools[id]
	if #s.ids == 0 or not pool or #pool.entries == 0 then
		counters.missing = counters.missing + 1
		warnOnce("noasset:" .. id, id .. " has no asset id yet (sound.py register, then build)")
		return nil
	end
	if s.looped then
		Sound.start(id)
		return pool.entries[1]
	end
	local t = now()
	if s.cooldown > 0 and lastPlay[id] and t - lastPlay[id] < s.cooldown then
		counters.cooled = counters.cooled + 1
		return nil
	end
	purge(t)
	local entry = pickEntry(s, pool, t)
	local total, inGroup = #active, 0
	for _, v in ipairs(active) do
		if v.group == s.group then
			inGroup = inGroup + 1
		end
	end
	local cap = Map.voices.perGroup[s.group]
	if entry == nil then
		entry = oldestOwn(pool, t)
		stopEntry(entry)
		counters.stolen = counters.stolen + 1
	elseif total >= Map.voices.max or (cap and inGroup >= cap) then
		local victim = findVictim(s, cap ~= nil and inGroup >= cap)
		if victim == nil then
			counters.dropped = counters.dropped + 1
			return nil
		end
		stopEntry(victim.entry)
		counters.stolen = counters.stolen + 1
	end
	local inst = entry.inst
	local lo, hi = s.pitch[1], s.pitch[2]
	local pitch = (lo + (hi - lo) * math.random()) * (opts.pitch or 1)
	inst.PlaybackSpeed = pitch
	inst.Volume = clamp(s.volume * dbToGain(opts.gainDb or 0), 0, 10)
	local target = opts.at
	if target == nil and s.space == "3d" then
		target = emitters[s.emitter]
		if target == nil then
			warnOnce("emit:" .. tostring(s.emitter), "no emitter for role " .. tostring(s.emitter) .. "; " .. id .. " plays 2D (Sound.setEmitter)")
		end
	end
	inst.Parent = target or folder
	inst.TimePosition = 0
	inst:Play()
	local len = (inst.TimeLength and inst.TimeLength > 0) and inst.TimeLength or s.length
	entry.startedAt = t
	entry.endsAt = t + len / pitch
	pool.lastVar = entry.var
	table.insert(active, { id = id, entry = entry, tier = s.tier, group = s.group, startedAt = t })
	if s.layer3d and pool.layer then
		local em = emitters[s.layer3d.emitter]
		if em then
			local L = pool.layer
			L.PlaybackSpeed = pitch
			L.Volume = clamp(inst.Volume * dbToGain(s.layer3d.gainDb), 0, 10)
			L.Parent = em
			L.TimePosition = 0
			L:Play()
		end
	end
	for _, r in ipairs(Map.ducking) do
		if r.sounds[id] or inChain(s.group, r.groups) then
			ruleUntil[r.name] = math.max(ruleUntil[r.name] or 0, entry.endsAt + r.hold)
		end
	end
	lastPlay[id] = t
	counters.played = counters.played + 1
	return entry
end

function Sound.start(id)
	local s = Map and Map.sounds[id]
	if not s or not s.looped then
		warnOnce("noloop:" .. tostring(id), tostring(id) .. " is not a looped sound")
		return
	end
	local pool = pools[id]
	if #s.ids == 0 or not pool or #pool.entries == 0 then
		counters.missing = counters.missing + 1
		warnOnce("noasset:" .. id, id .. " has no asset id yet (sound.py register, then build)")
		return
	end
	loops[id] = true
	applyLoop(id)
	local inst = pool.entries[1].inst
	local target = nil
	if s.space == "3d" then
		target = emitters[s.emitter]
		if target == nil then
			warnOnce("emit:" .. tostring(s.emitter), "no emitter for role " .. tostring(s.emitter) .. "; " .. id .. " plays 2D (Sound.setEmitter)")
		end
	end
	inst.Parent = target or folder
	if not inst.IsPlaying then
		inst:Play()
	end
end

function Sound.stop(id)
	loops[id] = nil
	local pool = pools[id]
	if not pool then
		return
	end
	for _, e in ipairs(pool.entries) do
		stopEntry(e)
	end
	if pool.layer then
		pool.layer:Stop()
	end
end

function Sound.toggle(id)
	if loops[id] then
		Sound.stop(id)
	else
		Sound.start(id)
	end
end

local function runEvent(name, ev, ctx)
	ctx = ctx or {}
	local pitch = ev.pitch or 1
	if ev.pitchStep then
		local t, rs = now(), repeatState[name]
		if rs and t - rs.at < 1.5 then
			rs.n = rs.n + 1
		else
			rs = { n = 0 }
			repeatState[name] = rs
		end
		rs.at = t
		pitch = pitch * (1 + ev.pitchStep * (ctx.n or rs.n))
	end
	local h = nil
	if ev.play then
		h = Sound.play(ev.play, { pitch = pitch * (ctx.pitch or 1), at = ctx.at, gainDb = ctx.gainDb })
	end
	if ev.toggle then
		Sound.toggle(ev.toggle)
	end
	if ev.start then
		for _, id in ipairs(ev.start) do
			Sound.start(id)
		end
	end
	if ev.stop then
		for _, id in ipairs(ev.stop) do
			Sound.stop(id)
		end
	end
	return h
end

function Sound.event(name, ctx)
	local ev = Map and Map.events[name]
	if not ev then
		warnOnce("noev:" .. tostring(name), "event " .. tostring(name) .. " is not in RR_SoundMap")
		return nil
	end
	if ev.via == "feel" and feelConnected then
		counters.ignored = counters.ignored + 1
		warnOnce("viafeel:" .. name, name .. " plays through RR_Feel; call Feel.play, not Sound.event")
		return nil
	end
	return runEvent(name, ev, ctx)
end

local function onCue(eventName, ch)
	if type(ch) ~= "table" or not ch.sfx then
		return
	end
	local ev = Map.events[eventName]
	if ev and ev.via == "feel" then
		runEvent(eventName, ev, nil)
	elseif Map.sounds[ch.sfx] then
		warnOnce("cue:" .. tostring(eventName), "feel event " .. tostring(eventName) .. " cues " .. ch.sfx .. " without a feel mapping in RR_SoundMap; playing it directly")
		Sound.play(ch.sfx)
	else
		warnOnce("cuesfx:" .. tostring(ch.sfx), "feel cue " .. tostring(ch.sfx) .. " has no sound in RR_SoundMap")
	end
end
Sound._onCue = onCue

function Sound.setSpeed(speed)
	for _, sl in ipairs(Map.speed) do
		local ratio = speed / sl.ref
		local rate = clamp(ratio, sl.rate[1], sl.rate[2])
		local gain = dbToGain(sl.slope * 20 * math.log10(math.max(ratio, 0.001)))
		local fade = 1
		if sl.silentBelow > 0 then
			fade = clamp((speed - sl.silentBelow) / sl.silentBelow, 0, 1)
		end
		speedState[sl.sound] = { rate = rate, gain = gain * fade }
		if loops[sl.sound] then
			applyLoop(sl.sound)
		end
	end
end

function Sound.setEmitter(role, inst)
	emitters[role] = inst
end

function Sound.setSetting(name, v)
	settings[name] = clamp(v, 0, 1)
	for g in pairs(groups) do
		applyGroup(g)
	end
end

function Sound.duck(ruleName, seconds)
	ruleUntil[ruleName] = now() + (seconds or 1)
end

function Sound.step(dt)
	local t = now()
	for _, st in pairs(gstate) do
		st.target = 0
	end
	for _, r in ipairs(Map.ducking) do
		if (ruleUntil[r.name] or 0) > t then
			for g, d in pairs(r.duck) do
				local st = gstate[g]
				if st and d < st.target then
					st.target = d
					st.down = -d / r.attack
					st.up = -d / r.release
				end
			end
		end
	end
	for g, st in pairs(gstate) do
		if st.db > st.target then
			st.db = math.max(st.target, st.db - st.down * dt)
			applyGroup(g)
		elseif st.db < st.target then
			st.db = math.min(st.target, st.db + st.up * dt)
			applyGroup(g)
		end
	end
	purge(t)
end

function Sound.stats()
	local ducks = {}
	for g, st in pairs(gstate) do
		ducks[g] = st.db
	end
	purge(now())
	return {
		played = counters.played, dropped = counters.dropped, stolen = counters.stolen, cooled = counters.cooled,
		missing = counters.missing, ignored = counters.ignored, active = #active, ducks = ducks,
	}
end

function Sound.stopAll()
	for id in pairs(pools) do
		Sound.stop(id)
	end
	active = {}
end

function Sound.destroy()
	for _, c in ipairs(conns) do
		c:Disconnect()
	end
	conns = {}
	for _, pool in pairs(pools) do
		for _, e in ipairs(pool.entries) do
			e.inst:Destroy()
		end
		if pool.layer then
			pool.layer:Destroy()
		end
	end
	groups, parentOf, settingOf, gstate = {}, {}, {}, {}
	pools, active, loops, emitters = {}, {}, {}, {}
	lastPlay, repeatState, ruleUntil, speedState, warned = {}, {}, {}, {}, {}
	counters = { played = 0, dropped = 0, stolen = 0, cooled = 0, missing = 0, ignored = 0 }
	feelConnected = false
	Map = nil
end

function Sound.init(map, opts)
	opts = opts or {}
	if not RunService:IsClient() then
		warn("[RR_Sound] runs on the client only (tech.streaming.sfx_pool): require it from a LocalScript")
		return nil
	end
	Sound.destroy()
	Map = map
	folder = opts.folder or SoundService:FindFirstChild("RR_SoundPool")
	if not folder then
		folder = Instance.new("Folder")
		folder.Name = "RR_SoundPool"
		folder.Parent = SoundService
	end
	local mix = SoundService:FindFirstChild("RR_Mix")
	if not mix then
		mix = Instance.new("Folder")
		mix.Name = "RR_Mix"
		mix.Parent = SoundService
	end
	for _, g in ipairs(map.groups) do
		local parentInst = g.parent and groups[g.parent] or mix
		local sg = parentInst:FindFirstChild(g.name)
		if not sg then
			sg = Instance.new("SoundGroup")
			sg.Name = g.name
			sg.Parent = parentInst
		end
		groups[g.name] = sg
		parentOf[g.name] = g.parent
		settingOf[g.name] = g.setting
		gstate[g.name] = { db = 0, target = 0, down = 60, up = 30 }
	end
	for k, v in pairs(map.settings) do
		settings[k] = v
	end
	local preload = {}
	for id, s in pairs(map.sounds) do
		local pool = { entries = {}, lastVar = 0 }
		pools[id] = pool
		if #s.ids > 0 then
			local n = s.looped and 1 or math.max(s.voices, #s.ids)
			for i = 1, n do
				local inst = makeSound(id, s, i, false)
				table.insert(pool.entries, { inst = inst, var = ((i - 1) % #s.ids) + 1, endsAt = 0, startedAt = 0 })
				table.insert(preload, inst)
			end
			if s.layer3d then
				pool.layer = makeSound(id, s, 1, true)
			end
		end
	end
	task.spawn(function()
		pcall(function()
			game:GetService("ContentProvider"):PreloadAsync(preload)
		end)
	end)
	table.insert(conns, RunService.Heartbeat:Connect(function(dt)
		Sound.step(dt)
	end))
	if opts.feel and opts.feel.Cue then
		feelConnected = true
		table.insert(conns, opts.feel.Cue.Event:Connect(onCue))
	end
	for g in pairs(groups) do
		applyGroup(g)
	end
	if map.placeholders and map.placeholders > 0 then
		warn("[RR_Sound] " .. map.placeholders .. " PLACEHOLDER sounds in use (never ship them)")
	end
	return Sound
end

return Sound
